-- ============================================================
-- search_keyword 컬럼 추가는 ORACLE_FIX_SCHEMA.sql에 통합되었습니다.
-- (컬럼이 이미 있으면 건너뛰는 PL/SQL 블록)
-- 단독으로만 적용하려면 아래 한 줄을 직접 실행할 수 있습니다.
-- ============================================================
-- ALTER TABLE recommendation_books ADD (search_keyword VARCHAR2(500 CHAR));
