-- ============================================================
-- USERS(없을 때만) + book_reviews (도서 별점·리뷰)
-- 실행: APP_USER 로 접속 → 전체 실행(F5)
--
-- spring.jpa.hibernate.ddl-auto=none 이면 Hibernate가 users를
-- 안 만들어서, FK(REFERENCES users)가 ORA-00942(PUBLIC.USERS)로 깨질 수 있음.
-- ============================================================

-- 0) users 테이블이 없으면 생성 (com.mindlink.domain.User 와 맞춤)
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE UPPER(table_name) = 'USERS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE users (
        id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name         VARCHAR2(50 CHAR)  NOT NULL,
        email        VARCHAR2(100 CHAR) NOT NULL,
        password     VARCHAR2(200 CHAR) NOT NULL,
        created_at   TIMESTAMP            NOT NULL
      )
    ]';
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uk_users_email ON users(email)';
  END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE book_reviews CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE book_reviews (
    id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     NUMBER          NOT NULL,
    book_link   VARCHAR2(2000)  NOT NULL,
    book_title  VARCHAR2(500),
    rating      NUMBER(1)       NOT NULL,
    content     VARCHAR2(1000),
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_br_user    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_br_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_br_user_book UNIQUE (user_id, book_link)
);

CREATE INDEX idx_br_book_link ON book_reviews(book_link);

COMMIT;
