-- =============================================================================
-- Mind-Link · AI 종합 보고서(위로 편지) 테이블 생성 — 서상원
--
-- 실행 계정: APP_USER (예: APP_USER / AppUser1234)
-- 전제: sql/ORACLE_SETUP.sql 을 먼저 실행해 users 테이블이 존재해야 한다.
--
-- 구성
--   1) care_reports        — 보고서 본문 + 스냅샷 + 위험 등급
--   2) care_daily_inputs   — (legacy) 더 이상 애플리케이션에서 쓰지 않음. 기존 환경 호환용 DDL 만 유지.
--   3) 인덱스 — 사용자별 최신순 조회, 24시간 한도 검사
--
-- 모든 DDL 은 「이미 있으면 무시」 패턴(PL/SQL 익명블록)으로 작성. 반복 실행 안전.
-- =============================================================================

ALTER SESSION SET NLS_LENGTH_SEMANTICS=CHAR;

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'CARE_REPORTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE care_reports (
        id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id       NUMBER             NOT NULL,
        snapshot_json CLOB,
        letter_body   CLOB               NOT NULL,
        risk_level    VARCHAR2(20 CHAR)  DEFAULT 'NORMAL' NOT NULL,
        themes        VARCHAR2(500 CHAR),
        created_at    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_care_reports_user
          FOREIGN KEY (user_id) REFERENCES users(id),
        CONSTRAINT chk_care_reports_risk
          CHECK (risk_level IN ('NORMAL', 'ELEVATED', 'CRISIS'))
      )
    ]';
  END IF;
END;
/

-- (legacy) care_daily_inputs — 어플리케이션에서 더 이상 INSERT/SELECT 하지 않는다.
-- 기존 운영 DB 호환을 위해 테이블이 이미 있어도 DROP 하지 않으나, 새 환경에서는 생성할 필요가 없다.
-- 신규 환경에서 굳이 만들고 싶다면 아래 블록의 주석을 풀어 실행.
-- DECLARE
--   c NUMBER;
-- BEGIN
--   SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'CARE_DAILY_INPUTS';
--   IF c = 0 THEN
--     EXECUTE IMMEDIATE q'[
--       CREATE TABLE care_daily_inputs (
--         id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--         user_id         NUMBER             NOT NULL,
--         input_date      DATE               NOT NULL,
--         mood            VARCHAR2(500 CHAR),
--         hardship        VARCHAR2(1000 CHAR),
--         current_thought VARCHAR2(1000 CHAR),
--         created_at      TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
--         CONSTRAINT fk_care_daily_inputs_user
--           FOREIGN KEY (user_id) REFERENCES users(id)
--       )
--     ]';
--   END IF;
-- END;
-- /

-- 인덱스 — 24시간 한도 검사와 사용자별 최신순 조회를 빠르게
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_indexes WHERE index_name = 'IDX_CARE_REPORTS_USER_CREATED';
  IF c = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_care_reports_user_created ON care_reports (user_id, created_at)';
  END IF;

END;
/

COMMIT;

-- 확인용 SELECT (필요 시 주석 해제)
-- SELECT table_name FROM user_tables WHERE table_name = 'CARE_REPORTS';
-- SELECT COUNT(*) FROM care_reports;
