-- =============================================================================
-- Mind-Link · 커뮤니티 3D 클러스터링 — DDL + 페르소나 시드 (통합) — 서상원
--
-- 실행 계정: APP_USER
-- 전제: sql/ORACLE_SETUP.sql 을 먼저 실행해 users 테이블이 존재.
--
-- 구성 (한 파일에서 순서대로 실행)
--   §1. DDL — user_assessment_profiles (클러스터 매칭방 테이블은 미사용이라 제외)
--   §2. 인덱스 — cluster_id, persona_key, UNIQUE(user_id)
--   §3. 페르소나 시드 — 30 종 × 7 명 = 210 합성 프로필
--        · 1차 시드(stable_calm, exam_stress …) 와 키가 100% 다름
--        · 카탈로그: docs/persona-catalog.md
--        · 시드용 임시 cluster_id (서버 K-Means 가 덮어쓴다):
--            0 = 안정·회복,  1 = 스트레스 우세,  2 = 우울 우세,
--            3 = 불안 우세,  4 = 복합·번아웃,    5 = 중간·혼합
--   §4. 확인용 SELECT 4 개
--
-- 모든 DDL 은 「있으면 스킵」 패턴. §3 시드는 DELETE 선행으로 재실행 안전.
-- =============================================================================

ALTER SESSION SET NLS_LENGTH_SEMANTICS=CHAR;

-- =============================================================================
-- §1. user_assessment_profiles
-- =============================================================================
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'USER_ASSESSMENT_PROFILES';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE user_assessment_profiles (
        id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id           NUMBER,                                  -- 실사용자면 users.id, 합성이면 NULL
        persona_key       VARCHAR2(40 CHAR)  NOT NULL,             -- 페르소나 식별자(스네이크)
        persona_label     VARCHAR2(80 CHAR)  NOT NULL,             -- 한국어 라벨
        persona_story     VARCHAR2(500 CHAR),                      -- 2~3 문장 소개
        stress_score      NUMBER(5,1)        NOT NULL,             -- 원점수 (PSS 만점 40)
        depression_score  NUMBER(5,1)        NOT NULL,             -- 원점수 (PHQ-9 만점 27)
        anxiety_score     NUMBER(5,1)        NOT NULL,             -- 원점수 (GAD-7 만점 21)
        stress_norm       NUMBER(6,4)        NOT NULL,             -- 0~1
        depression_norm   NUMBER(6,4)        NOT NULL,             -- 0~1
        anxiety_norm      NUMBER(6,4)        NOT NULL,             -- 0~1
        cluster_id        NUMBER(3),                               -- K-Means 결과 (nullable)
        is_synthetic      NUMBER(1)          DEFAULT 1 NOT NULL,   -- 1=합성, 0=실사용자
        created_at        TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        updated_at        TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT chk_uap_synthetic CHECK (is_synthetic IN (0,1)),
        CONSTRAINT chk_uap_stress    CHECK (stress_score BETWEEN 0 AND 40),
        CONSTRAINT chk_uap_depress   CHECK (depression_score BETWEEN 0 AND 27),
        CONSTRAINT chk_uap_anxiety   CHECK (anxiety_score BETWEEN 0 AND 21),
        CONSTRAINT chk_uap_norm_s    CHECK (stress_norm BETWEEN 0 AND 1),
        CONSTRAINT chk_uap_norm_d    CHECK (depression_norm BETWEEN 0 AND 1),
        CONSTRAINT chk_uap_norm_a    CHECK (anxiety_norm BETWEEN 0 AND 1)
      )
    ]';
  END IF;
END;
/

-- 실사용자 1인 1행 보장 (NULL 은 무제한 중복 허용 — 합성에는 영향 없음)
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_indexes WHERE index_name = 'UQ_UAP_USER';
  IF c = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_uap_user ON user_assessment_profiles (user_id)';
  END IF;
END;
/

-- 참고: 클러스터 기반 "비슷한 마음 모임"(매칭방) 테이블은 향후 예비 기능으로,
--       현재 Java 코드에서 사용하지 않아 DDL 을 두지 않습니다(생성 시 clustering_rooms 등으로 별도 정의 예정).

-- =============================================================================
-- §2. 인덱스
-- =============================================================================
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_indexes WHERE index_name = 'IDX_UAP_CLUSTER';
  IF c = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_uap_cluster ON user_assessment_profiles (cluster_id)';
  END IF;

  SELECT COUNT(*) INTO c FROM user_indexes WHERE index_name = 'IDX_UAP_PERSONA';
  IF c = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_uap_persona ON user_assessment_profiles (persona_key)';
  END IF;
END;
/

COMMIT;

-- =============================================================================
-- §3. 페르소나 시드 (30 종 × 7 명 = 210 행)
--   · 점수 만점: stress 40, depression 27, anxiety 21 (정규화 ÷40, ÷27, ÷21)
--   · 변형 7 명: 기본 점수 ± DBMS_RANDOM(-2.5, +2.5) 흔들기, 만점 클램프
--   · 맥락: 20대 한국 대학·팀플·자취·알바·취업·연애
-- =============================================================================

-- 합성 데이터 초기화 (재실행 안전)
DELETE FROM user_assessment_profiles WHERE is_synthetic = 1;
COMMIT;

DECLARE
  TYPE t_pers IS RECORD (
    k     VARCHAR2(40),
    lbl   VARCHAR2(80),
    story VARCHAR2(500),
    s     NUMBER,
    d     NUMBER,
    a     NUMBER,
    cid   NUMBER
  );
  TYPE t_pers_arr IS TABLE OF t_pers INDEX BY PLS_INTEGER;
  arr t_pers_arr;

  v_s      NUMBER;
  v_d      NUMBER;
  v_a      NUMBER;
  v_norm_s NUMBER;
  v_norm_d NUMBER;
  v_norm_a NUMBER;

  C_S_MAX CONSTANT NUMBER := 40;
  C_D_MAX CONSTANT NUMBER := 27;
  C_A_MAX CONSTANT NUMBER := 21;

  PROCEDURE add_pers(
    p_idx PLS_INTEGER,
    p_k VARCHAR2, p_lbl VARCHAR2, p_story VARCHAR2,
    p_s NUMBER, p_d NUMBER, p_a NUMBER, p_cid NUMBER
  ) IS
    rec t_pers;
  BEGIN
    rec.k := p_k; rec.lbl := p_lbl; rec.story := p_story;
    rec.s := p_s; rec.d := p_d; rec.a := p_a; rec.cid := p_cid;
    arr(p_idx) := rec;
  END;

BEGIN
  ----------------------------------------------------------------------------
  -- 0 = 안정·회복
  ----------------------------------------------------------------------------
  add_pers(1,
    'morning_jogger', '새벽 러닝 안정형',
    '매일 새벽 5km 러닝과 일찍 잠드는 루틴을 1년 넘게 유지하고 있어요. 큰 스트레스 사건이 있어도 하루 이틀이면 다시 페이스를 잡고 평정심으로 돌아옵니다.',
     9,  4,  4, 0);
  add_pers(2,
    'study_group_steady', '스터디 안정형',
    '학기 초마다 4명짜리 스터디를 꾸려 시험 일정과 과제 마감을 함께 끌고 갑니다. 혼자였으면 흔들렸을 시기에도 동료의 페이스 덕에 무리 없이 학기를 마무리해요.',
    10,  5,  5, 0);
  add_pers(3,
    'cafe_journaler', '카페 일기형',
    '동네 카페에서 일주일에 두세 번 일기와 다음 주 계획을 정리하는 습관이 있어요. 생각이 글로 빠져나가면 머릿속 잡음이 줄어 다시 침착하게 돌아옵니다.',
     8,  5,  4, 0);
  add_pers(4,
    'volunteer_warmth', '봉사 충전형',
    '격주 토요일 지역 아동센터에서 학습 봉사를 합니다. 누군가에게 도움이 된다는 감각이 자기 효능감을 채워 줘서 평소 정서가 안정적이에요.',
    10,  4,  3, 0);
  add_pers(5,
    'solo_traveler_calm', '혼행 회복형',
    '학기에 한 번씩 1박 혼자 여행을 떠나 사진을 찍고 책을 읽고 옵니다. 일상의 소음에서 잠시 벗어나는 리셋 의례가 정서 균형의 핵심이에요.',
    11,  6,  5, 0);

  ----------------------------------------------------------------------------
  -- 1 = 스트레스 우세
  ----------------------------------------------------------------------------
  add_pers(6,
    'thesis_crunch', '졸업논문 막판형',
    '졸업논문 마감이 한 달 앞으로 다가와 식사를 거르고 매달리는 날이 많아요. 어깨와 턱이 굳을 만큼 긴장도가 높지만 끝나면 풀린다는 걸 알아 버티는 중입니다.',
    31, 11, 10, 1);
  add_pers(7,
    'team_project_overload', '팀플 떠안기형',
    '팀플 조에서 다른 인원의 무임승차로 혼자 거의 모든 분량을 끌고 가고 있어요. 다음 발표를 잘 마쳐야 학점에 영향이 가지 않아 압박감이 큽니다.',
    30, 12, 11, 1);
  add_pers(8,
    'night_shift_alba', '야간 알바 누적형',
    '학교 수업과 야간·새벽 편의점 알바를 병행한 지 반 년이 넘었습니다. 만성 피로와 시간 부족으로 일상 결정마저 짜증이 섞이는 시기예요.',
    32, 13, 10, 1);
  add_pers(9,
    'internship_pressure', '인턴 전환 평가형',
    '인턴 6개월 끝나는 평가에서 정규직 전환 여부가 정해져 매주 출근이 면접 같아요. 잘 보이려고 자기 검열이 늘어 퇴근 후에도 일이 머리에서 안 떠납니다.',
    29, 12, 12, 1);
  add_pers(10,
    'landlord_dispute', '자취 분쟁형',
    '보증금 반환과 층간 소음으로 집주인과 분쟁이 두 달째 진행 중이에요. 집이 쉬는 공간이 아니라 또 다른 일거리가 되어 신경이 늘 곤두서 있어요.',
    28, 11, 11, 1);

  ----------------------------------------------------------------------------
  -- 2 = 우울 우세
  ----------------------------------------------------------------------------
  add_pers(11,
    'dropout_doubt', '휴학 자책형',
    '한 학기 휴학을 했지만 계획대로 자격증·운동·여행 어느 것도 못 했어요. SNS 속 또래의 결과물과 비교하며 자기 자신을 자주 깎아내립니다.',
    17, 21,  9, 2);
  add_pers(12,
    'hometown_lonely', '자취 향수형',
    '본가에서 멀리 떨어진 학교로 진학해 4년째 자취 중입니다. 가족과 고향 친구가 그리워 의욕이 자주 빠져나가고 혼자 끓이는 라면이 점점 무거워져요.',
    16, 20,  8, 2);
  add_pers(13,
    'unrequited_quiet', '짝사랑 침잠형',
    '오래 마음에 두던 사람과의 관계가 끝내 시작되지 않은 채 멀어졌습니다. 같은 학과·동아리에서 마주칠 때마다 마음이 가라앉아 일상 텐션이 낮아져요.',
    18, 19,  8, 2);
  add_pers(14,
    'gpa_drop_slump', '학점 하락 슬럼프형',
    'F와 재수강이 누적되면서 졸업 학점에 대한 자신감이 무너졌어요. ''나는 어차피 안 된다''는 생각이 자주 올라와 새 학기에 등록하는 일조차 망설입니다.',
    18, 22, 10, 2);
  add_pers(15,
    'pet_loss_grief', '반려동물 상실형',
    '10년을 함께한 반려동물을 떠나보낸 지 두 달이 채 안 됐습니다. 빈자리가 너무 크게 느껴져 강의·약속 후 집에 돌아오면 한참을 멍하니 있어요.',
    17, 23,  9, 2);

  ----------------------------------------------------------------------------
  -- 3 = 불안 우세
  ----------------------------------------------------------------------------
  add_pers(16,
    'job_search_loop', '취준 루프형',
    '자소서 50통, 면접 7번, 최종 탈락 3번을 반복하는 한 학기를 보내고 있어요. 다음 결과 발표일이 가까워질수록 가슴이 빠르게 뛰고 자다 깨는 일이 잦습니다.',
    18, 11, 17, 3);
  add_pers(17,
    'presentation_dread', '발표 공포형',
    '다음 주 학회 발표를 위해 슬라이드를 다듬는 중인데 무대 위 자신을 상상하면 손이 차가워져요. 말이 막힐 시나리오를 미리 떠올려 잠들기까지 시간이 오래 걸립니다.',
    17, 10, 18, 3);
  add_pers(18,
    'gpa_perfection_anxiety', '학점 완벽 불안형',
    'A+가 아닌 학점이 한 과목만 떠도 인생 전체가 흔들리는 기분이 들어요. 시험 전날 위경련이 종종 와 약을 챙겨 가는 게 일상이 됐습니다.',
    17, 12, 16, 3);
  add_pers(19,
    'ldr_anxious', '장거리 연애 불안형',
    '교환학생으로 떠난 연인과 8시간 시차의 장거리 연애를 이어 가고 있어요. 답장이 늦으면 별별 상상이 떠올라 일상 집중이 어려워집니다.',
    16, 10, 17, 3);
  add_pers(20,
    'oce_first_living', '첫 자취 적응형',
    '첫 자취를 시작한 지 두 달, 밤마다 복도 발소리와 창문 소리에 깨곤 해요. 작은 소음에도 신경이 곤두서 다음 날 일과가 평소보다 무겁게 시작됩니다.',
    18, 11, 18, 3);

  ----------------------------------------------------------------------------
  -- 4 = 복합·번아웃
  ----------------------------------------------------------------------------
  add_pers(21,
    'dual_degree_overload', '복수전공 과부하형',
    '복수전공·동아리 임원·주 3회 알바를 동시에 굴리는 학기가 두 학기째예요. 한 가지를 놓으면 도미노처럼 무너질 것 같아 모든 의욕이 동시에 떨어진 상태입니다.',
    31, 21, 15, 4);
  add_pers(22,
    'creator_overcommit', '콘텐츠 번아웃형',
    '학교 공부와 함께 유튜브·블로그를 주 5회 업로드 일정으로 운영해 왔어요. 댓글·조회수에 기분이 좌우되고, 회복 시간 없이 다음 콘텐츠를 준비하느라 모든 게 소진되는 느낌입니다.',
    32, 22, 16, 4);
  add_pers(23,
    'family_caretaker_student', '가족 부양 학생형',
    '학업과 동시에 아픈 부모님 병원 동행·집안 살림까지 챙기는 위치에 있어요. 책임감과 무력감이 동시에 커서 누구에게 도움을 청해도 미안함부터 올라옵니다.',
    33, 23, 14, 4);
  add_pers(24,
    'breakup_then_finals', '이별·시험 동시형',
    '기말고사 2주 전 오래 사귄 연인과 헤어진 직후 시험을 치렀습니다. 슬픔을 미뤄 두려다 시험까지 망쳐 자기 자신에 대한 신뢰가 흔들리는 시기예요.',
    30, 22, 15, 4);
  add_pers(25,
    'eating_disorder_recurring', '식이 재발형',
    '고등학생 때 한 차례 회복했던 식이 통제 습관이 학업 스트레스와 함께 다시 돌아오는 신호를 느껴요. 의지로 누르려 할수록 죄책감과 긴장이 같이 올라옵니다.',
    31, 22, 17, 4);

  ----------------------------------------------------------------------------
  -- 5 = 중간·혼합
  ----------------------------------------------------------------------------
  add_pers(26,
    'weekend_recharge_only', '주말만 충전형',
    '평일은 큰 문제 없이 굴러가지만 금요일 저녁이 되면 한 주의 누적 피로가 한꺼번에 몰려와요. 토요일 하루를 통째로 자야 다음 주가 시작되는 패턴이 굳어졌습니다.',
    18, 12, 10, 5);
  add_pers(27,
    'social_chameleon', '관계 위장형',
    '학과 모임·동아리·알바 사람들 사이에서 모두 다른 가면을 쓰는 데 익숙해요. 자리 자체는 즐겁지만 집에 돌아오면 자신이 누구인지 흐릿해지는 피로감이 남습니다.',
    19, 13, 11, 5);
  add_pers(28,
    'screen_time_drift', '디지털 표류형',
    '잠들기 전 숏폼과 SNS를 한 시간 이상 보는 습관이 굳어져 점점 수면 시간이 줄고 있어요. 큰 문제는 없지만 낮 동안의 집중력이 조금씩 떨어지는 게 느껴집니다.',
    20, 13, 10, 5);
  add_pers(29,
    'mild_imposter_intern', '약한 가면 증후군형',
    '인턴 동기들이 다 자기보다 똑똑해 보여 자신은 운으로 뽑힌 것 같다는 생각이 자주 듭니다. 큰 실수는 없지만 회의에서 말을 아끼게 되고 자신감이 느리게 깎입니다.',
    17, 13, 11, 5);
  add_pers(30,
    'room_clutter_lethargy', '방 정돈 미루기형',
    '방의 어지러움이 마음의 어지러움과 정비례한다는 걸 알면서도 치울 에너지가 잘 안 모입니다. 한 번 정리하면 며칠은 가뿐하지만 다시 쌓이는 사이클을 반복 중이에요.',
    19, 14, 11, 5);

  ----------------------------------------------------------------------------
  -- 30 페르소나 × 7 명 = 210 row 적재
  ----------------------------------------------------------------------------
  FOR i IN 1 .. arr.COUNT LOOP
    FOR v IN 1 .. 7 LOOP
      v_s := ROUND(GREATEST(0, LEAST(C_S_MAX, arr(i).s + DBMS_RANDOM.VALUE(-2.5, 2.5))));
      v_d := ROUND(GREATEST(0, LEAST(C_D_MAX, arr(i).d + DBMS_RANDOM.VALUE(-2.5, 2.5))));
      v_a := ROUND(GREATEST(0, LEAST(C_A_MAX, arr(i).a + DBMS_RANDOM.VALUE(-2.5, 2.5))));

      v_norm_s := ROUND(v_s / C_S_MAX, 4);
      v_norm_d := ROUND(v_d / C_D_MAX, 4);
      v_norm_a := ROUND(v_a / C_A_MAX, 4);

      INSERT INTO user_assessment_profiles (
        user_id, persona_key, persona_label, persona_story,
        stress_score, depression_score, anxiety_score,
        stress_norm, depression_norm, anxiety_norm,
        cluster_id, is_synthetic, created_at, updated_at
      ) VALUES (
        NULL, arr(i).k, arr(i).lbl, arr(i).story,
        v_s, v_d, v_a,
        v_norm_s, v_norm_d, v_norm_a,
        arr(i).cid, 1, SYSTIMESTAMP, SYSTIMESTAMP
      );
    END LOOP;
  END LOOP;
END;
/

COMMIT;

-- =============================================================================
-- §4. 확인용 SELECT (4 개)
-- =============================================================================

-- ① 총 210건
SELECT COUNT(*) AS total_rows FROM user_assessment_profiles WHERE is_synthetic = 1;

-- ② 페르소나별 평균 좌표 (30 행, cnt=7 each)
SELECT persona_key,
       COUNT(*)                          AS cnt,
       ROUND(AVG(stress_norm),3)         AS avg_s,
       ROUND(AVG(depression_norm),3)     AS avg_d,
       ROUND(AVG(anxiety_norm),3)        AS avg_a
FROM   user_assessment_profiles
WHERE  is_synthetic = 1
GROUP BY persona_key
ORDER BY persona_key;

-- ③ 시드 집단별 인원·중심좌표 (6 행)
SELECT cluster_id,
       COUNT(*)                          AS members,
       ROUND(AVG(stress_norm),3)         AS centroid_s,
       ROUND(AVG(depression_norm),3)     AS centroid_d,
       ROUND(AVG(anxiety_norm),3)        AS centroid_a
FROM   user_assessment_profiles
WHERE  is_synthetic = 1
GROUP BY cluster_id
ORDER BY cluster_id;

-- ④ 샘플 20건 (집단별 정렬)
SELECT id, persona_label,
       stress_norm, depression_norm, anxiety_norm,
       cluster_id
FROM   user_assessment_profiles
WHERE  is_synthetic = 1
ORDER BY cluster_id, id
FETCH FIRST 20 ROWS ONLY;
