-- =============================================================================
-- Mind-Link · 모니터링 + 알림 (assessment_results, user_alerts, 댓글 답글)
-- 실행 계정: APP_USER
-- 선행: 01_schema/ORACLE_SETUP.sql, 02_features/ASSESSMENT_SEED.sql
--
-- 구 MONITORING_SETUP.sql + ALERTS_EXTEND.sql 를 하나로 통합.
-- 신규 설치는 이 파일 하나로 최종 스키마(링크 컬럼·확장 alert_type 포함)가 완성됩니다.
-- 기존 DB는 멱등 ALTER 로 누락 컬럼·제약만 보강합니다.
-- 트러블슈팅(ORA-00904/01400)은 archive/MONITORING_FIX.sql · MONITORING_REBUILD.sql 참고.
-- =============================================================================

SET SERVEROUTPUT ON;

-- ── 1. assessment_results: 자가진단 결과 이력 (로그인 사용자만 저장) ──────────
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'ASSESSMENT_RESULTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE assessment_results (
        id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id         NUMBER               NOT NULL,
        type_key        VARCHAR2(50 CHAR)    NOT NULL,
        type_name       VARCHAR2(100 CHAR),
        score           NUMBER,
        score_level     VARCHAR2(30 CHAR),
        result_level    VARCHAR2(30 CHAR),
        is_high_risk    NUMBER(1) DEFAULT 0  NOT NULL,
        personal_score  NUMBER,
        personal_level  VARCHAR2(30 CHAR),
        work_score      NUMBER,
        work_level      VARCHAR2(30 CHAR),
        created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_ar_user FOREIGN KEY (user_id)
          REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT chk_ar_high_risk CHECK (is_high_risk IN (0, 1))
      )
    ]';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ar_user_type ON assessment_results(user_id, type_key, created_at)';
  END IF;
END;
/

-- ── 1b. assessment_results 컬럼 보정 (Hibernate 구스키마 등 JPA 불일치) ───────
DECLARE
  n NUMBER;
  PROCEDURE add_col_if_missing(p_col VARCHAR2, p_ddl VARCHAR2) IS
    c NUMBER;
  BEGIN
    SELECT COUNT(*) INTO c FROM user_tab_columns
     WHERE table_name = 'ASSESSMENT_RESULTS' AND column_name = UPPER(p_col);
    IF c = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE assessment_results ADD (' || p_ddl || ')';
      DBMS_OUTPUT.PUT_LINE('OK: assessment_results.' || LOWER(p_col) || ' added');
    END IF;
  END;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'ASSESSMENT_RESULTS';
  IF n = 0 THEN
    RETURN;
  END IF;

  add_col_if_missing('TYPE_KEY',       'type_key VARCHAR2(50 CHAR)');
  add_col_if_missing('TYPE_NAME',      'type_name VARCHAR2(100 CHAR)');
  add_col_if_missing('SCORE',          'score NUMBER');
  add_col_if_missing('SCORE_LEVEL',    'score_level VARCHAR2(30 CHAR)');
  add_col_if_missing('RESULT_LEVEL',   'result_level VARCHAR2(30 CHAR)');
  add_col_if_missing('IS_HIGH_RISK',   'is_high_risk NUMBER(1) DEFAULT 0');
  add_col_if_missing('PERSONAL_SCORE', 'personal_score NUMBER');
  add_col_if_missing('PERSONAL_LEVEL', 'personal_level VARCHAR2(30 CHAR)');
  add_col_if_missing('WORK_SCORE',     'work_score NUMBER');
  add_col_if_missing('WORK_LEVEL',     'work_level VARCHAR2(30 CHAR)');

  DECLARE
    n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM user_tab_columns
     WHERE table_name = 'ASSESSMENT_RESULTS' AND column_name = 'CREATED_AT';
    IF n = 0 THEN
      SELECT COUNT(*) INTO n FROM user_tab_columns
       WHERE table_name = 'ASSESSMENT_RESULTS' AND column_name = 'COMPLETED_AT';
      IF n > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE assessment_results ADD (created_at TIMESTAMP DEFAULT SYSTIMESTAMP)';
        EXECUTE IMMEDIATE 'UPDATE assessment_results SET created_at = completed_at WHERE created_at IS NULL';
        DBMS_OUTPUT.PUT_LINE('OK: created_at added (copied from completed_at)');
      ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE assessment_results ADD (created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
        DBMS_OUTPUT.PUT_LINE('OK: created_at added');
      END IF;
    END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE q'[
      UPDATE assessment_results
         SET type_name = CASE type_key
           WHEN 'depression' THEN '우울증 (PHQ-9)'
           WHEN 'anxiety'    THEN '불안장애 (GAD-7)'
           WHEN 'stress'     THEN '스트레스 (PSS-10)'
           WHEN 'burnout'    THEN '번아웃 (CBI)'
           ELSE type_key
         END
       WHERE type_name IS NULL AND type_key IS NOT NULL
    ]';
    EXECUTE IMMEDIATE q'[
      UPDATE assessment_results
         SET result_level = NVL(score_level, NVL(personal_level, NVL(work_level, '미분류')))
       WHERE result_level IS NULL
    ]';
    EXECUTE IMMEDIATE q'[
      UPDATE assessment_results
         SET score_level = result_level
       WHERE score_level IS NULL AND result_level IS NOT NULL
    ]';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;

  BEGIN
    SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name = 'IDX_AR_USER_TYPE';
    IF n = 0 THEN
      EXECUTE IMMEDIATE 'CREATE INDEX idx_ar_user_type ON assessment_results(user_id, type_key, created_at)';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN NULL; -- 컬럼 미완료 시 인덱스 생략
  END;
END;
/

-- ── 2. user_alerts: 사용자 알림 (악화·고위험·커뮤니티·공지·관리자) ────────────
--   신규 설치는 링크 컬럼·확장 alert_type 까지 포함한 최종 스키마로 생성됩니다.
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'USER_ALERTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE user_alerts (
        id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id              NUMBER               NOT NULL,
        alert_type           VARCHAR2(30 CHAR)    NOT NULL,
        message              CLOB,
        assessment_result_id NUMBER,
        link_url             VARCHAR2(500 CHAR),
        title                VARCHAR2(200 CHAR),
        related_post_id      NUMBER,
        related_comment_id   NUMBER,
        notice_id            NUMBER,
        is_read              NUMBER(1) DEFAULT 0  NOT NULL,
        admin_confirmed      NUMBER(1) DEFAULT 0  NOT NULL,
        created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_ua_user   FOREIGN KEY (user_id)
          REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_ua_result FOREIGN KEY (assessment_result_id)
          REFERENCES assessment_results(id) ON DELETE SET NULL,
        CONSTRAINT chk_ua_type  CHECK (alert_type IN (
          'DETERIORATION', 'HIGH_RISK', 'RECOMMEND', 'IMPROVEMENT', 'IMPROVEMENT_MIN',
          'POST_COMMENT', 'COMMENT_REPLY', 'NOTICE', 'ADMIN_MESSAGE')),
        CONSTRAINT chk_ua_read  CHECK (is_read IN (0, 1)),
        CONSTRAINT chk_ua_confirmed CHECK (admin_confirmed IN (0, 1))
      )
    ]';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ua_user_read ON user_alerts(user_id, is_read, created_at)';
  END IF;
END;
/

-- ── 2b. user_alerts 링크·연관 ID 컬럼 보강 (기존 테이블 대상, 멱등) ───────────
DECLARE
  v_cnt NUMBER;
  PROCEDURE add_ua_col(p_col VARCHAR2, p_ddl VARCHAR2) IS
    c NUMBER;
  BEGIN
    SELECT COUNT(*) INTO c FROM user_tab_columns
     WHERE table_name = 'USER_ALERTS' AND column_name = UPPER(p_col);
    IF c = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE user_alerts ADD (' || p_ddl || ')';
    END IF;
  END;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'USER_ALERTS';
  IF v_cnt = 0 THEN
    RETURN;
  END IF;
  add_ua_col('LINK_URL',           'link_url VARCHAR2(500 CHAR)');
  add_ua_col('TITLE',              'title VARCHAR2(200 CHAR)');
  add_ua_col('RELATED_POST_ID',    'related_post_id NUMBER');
  add_ua_col('RELATED_COMMENT_ID', 'related_comment_id NUMBER');
  add_ua_col('NOTICE_ID',          'notice_id NUMBER');
  add_ua_col('ADMIN_CONFIRMED',    'admin_confirmed NUMBER(1) DEFAULT 0 NOT NULL');
END;
/

-- ── 2c. alert_type CHECK 제약을 최종 9종으로 정렬 (멱등) ──────────────────────
DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'USER_ALERTS';
  IF c = 0 THEN
    RETURN;
  END IF;
  SELECT COUNT(*) INTO c FROM user_constraints
   WHERE table_name = 'USER_ALERTS' AND constraint_name = 'CHK_UA_TYPE';
  IF c > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE user_alerts DROP CONSTRAINT chk_ua_type';
  END IF;
  EXECUTE IMMEDIATE q'[
    ALTER TABLE user_alerts ADD CONSTRAINT chk_ua_type CHECK (
      alert_type IN (
        'DETERIORATION', 'HIGH_RISK', 'RECOMMEND', 'IMPROVEMENT', 'IMPROVEMENT_MIN',
        'POST_COMMENT', 'COMMENT_REPLY', 'NOTICE', 'ADMIN_MESSAGE'
      )
    )
  ]';
END;
/

-- ── 3. post_comments 답글(parent_comment_id) ─────────────────────────────────
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
   WHERE table_name = 'POST_COMMENTS' AND column_name = 'PARENT_COMMENT_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE post_comments ADD (parent_comment_id NUMBER)';
    EXECUTE IMMEDIATE q'[
      ALTER TABLE post_comments ADD CONSTRAINT fk_pc_parent
        FOREIGN KEY (parent_comment_id) REFERENCES post_comments(id) ON DELETE CASCADE
    ]';
  END IF;
END;
/

COMMIT;
