-- =============================================================================
-- Mind-Link · Oracle 통합 스크립트 (한 파일)
-- 실행 계정: APP_USER (예: APP_USER / AppUser1234)
--
-- 전제: APP_USER 로 접속. 빈 스키마여도 섹션 0이 users·posts·공지 등 기본 테이블을 만듭니다.
--       (recommendation_books 만 Hibernate 등으로 이미 있을 때도 동작하도록 ALTER 는 조건부)
--
-- 구성
--   0) 기본 테이블 생성(없을 때만) — 실행 순서는 sql/README.md 참고
--   1) 스키마 보정 — 문자 길이, CLOB, recommendation_books.search_keyword (테이블 있을 때만 ALTER)
--   2) users role 보정(구 스키마) + book_reviews (users 존재 시에만 생성)
--   2b) 샘플 데이터 — 관리자 MERGE + 공지·게시글(해당 테이블이 모두 있을 때만)
--   3) recommendation_books 데이터 적재 (전량 재적재, 교보링크 세트)
--
-- 자가진단(김지훈): 본 파일 실행 후 02_features/ASSESSMENT_SEED.sql 을 별도 실행하세요. (전체 순서: sql/README.md)
-- 상담 예약(윤아연): 섹션 0에 bookings 테이블 포함 (Hibernate ddl-auto=none)
--
-- 데이터만 다시 넣고 싶다면: 섹션 3만 별도 복사해 실행해도 됨(전제 조건 동일).
-- 가벼운 20권 시드(수동 ISBN NULL 행만 교체)는 파일 맨 아래 주석 블록 참고.
-- =============================================================================

ALTER SESSION SET NLS_LENGTH_SEMANTICS=CHAR;

-- =============================================================================
-- 0. 기본 테이블 (없을 때만) — ddl-auto=none 이고 앱을 안 돌린 DB용
-- =============================================================================

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'USERS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE users (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        VARCHAR2(50 CHAR)  NOT NULL,
        email       VARCHAR2(100 CHAR) NOT NULL,
        password    VARCHAR2(255 CHAR) NOT NULL,
        role        VARCHAR2(20 CHAR)  DEFAULT 'USER' NOT NULL,
        created_at  TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT uq_users_email UNIQUE (email),
        CONSTRAINT chk_users_role CHECK (role IN ('USER', 'COUNSELOR', 'ADMIN'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POSTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE posts (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        author      VARCHAR2(50 CHAR)  NOT NULL,
        title       VARCHAR2(200 CHAR) NOT NULL,
        content     CLOB                 NOT NULL,
        category    VARCHAR2(30 CHAR)   NOT NULL,
        likes       NUMBER(10)          DEFAULT 0 NOT NULL,
        created_at  TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POST_COMMENTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE post_comments (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        post_id     NUMBER       NOT NULL,
        author      VARCHAR2(50 CHAR) NOT NULL,
        content     CLOB                NOT NULL,
        created_at  TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'REPORTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE reports (
        id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        reporter_id  NUMBER      NOT NULL,
        target_type  VARCHAR2(10 CHAR) NOT NULL,
        target_id    NUMBER      NOT NULL,
        reason       CLOB        NOT NULL,
        created_at   TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users(id),
        CONSTRAINT chk_reports_target_type CHECK (target_type IN ('POST', 'COMMENT'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'NOTICES';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE notices (
        id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category         VARCHAR2(30 CHAR)  NOT NULL,
        title            VARCHAR2(200 CHAR) NOT NULL,
        summary          VARCHAR2(500 CHAR) NOT NULL,
        content          CLOB                 NOT NULL,
        created_at       TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'ATTACHMENTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE attachments (
        id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_file_name VARCHAR2(255 CHAR) NOT NULL,
        stored_file_name    VARCHAR2(255 CHAR) NOT NULL,
        file_url            VARCHAR2(500 CHAR) NOT NULL,
        file_type           VARCHAR2(10 CHAR)  NOT NULL,
        file_size           NUMBER(20)         DEFAULT 0 NOT NULL,
        target_type         VARCHAR2(10 CHAR)  NOT NULL,
        target_id           NUMBER             NOT NULL,
        created_at          TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT chk_attachments_file_type CHECK (file_type IN ('IMAGE', 'VIDEO', 'LINK')),
        CONSTRAINT chk_attachments_target_type CHECK (target_type IN ('POST', 'COMMENT'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'BOOKINGS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE bookings (
        id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        center_name     VARCHAR2(200 CHAR) NOT NULL,
        center_title    VARCHAR2(100 CHAR),
        center_phone    VARCHAR2(30 CHAR),
        center_address  VARCHAR2(300 CHAR),
        user_id         NUMBER,
        name            VARCHAR2(50 CHAR)  NOT NULL,
        phone           VARCHAR2(30 CHAR)  NOT NULL,
        email           VARCHAR2(100 CHAR) NOT NULL,
        booking_date    DATE               NOT NULL,
        booking_time    VARCHAR2(8 CHAR)   NOT NULL,
        type            VARCHAR2(50 CHAR),
        memo            CLOB,
        status          VARCHAR2(20 CHAR)  DEFAULT 'REQUESTED' NOT NULL,
        created_at      TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id),
        CONSTRAINT chk_bookings_status CHECK (status IN ('REQUESTED', 'CONFIRMED', 'CANCELLED'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'RECOMMENDATION_BOOKS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE recommendation_books (
        id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        emotion        VARCHAR2(20 CHAR)   NOT NULL,
        title          VARCHAR2(1000 CHAR) NOT NULL,
        author         VARCHAR2(500 CHAR),
        publisher      VARCHAR2(500 CHAR),
        link           VARCHAR2(2000 CHAR),
        image          VARCHAR2(2000 CHAR),
        description    CLOB,
        isbn           VARCHAR2(50 CHAR),
        search_keyword VARCHAR2(500 CHAR),
        CONSTRAINT uq_rb_isbn UNIQUE (isbn),
        CONSTRAINT chk_rb_emotion CHECK (emotion IN (
          'DEPRESSION','STRESS','ANXIETY','LETHARGY','RELATIONSHIP','NORMAL'))
      )
    ]';
  END IF;
END;
/

-- =============================================================================
-- 1. 스키마 보정 (문자 길이 여유 + CLOB + search_keyword)
-- =============================================================================

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POSTS';
  IF c > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE posts MODIFY (author VARCHAR2(200 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE posts MODIFY (title VARCHAR2(1000 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE posts MODIFY (category VARCHAR2(200 CHAR))';
  END IF;
END;
/

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POST_COMMENTS';
  IF c > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE post_comments MODIFY (author VARCHAR2(200 CHAR))';
  END IF;
END;
/

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'RECOMMENDATION_BOOKS';
  IF c > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (title VARCHAR2(1000 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (author VARCHAR2(500 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (publisher VARCHAR2(500 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (link VARCHAR2(2000 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (image VARCHAR2(2000 CHAR))';
  END IF;
END;
/

DECLARE
  v_nullable VARCHAR2(1);
BEGIN
  SELECT nullable INTO v_nullable
    FROM user_tab_columns
   WHERE table_name = 'RECOMMENDATION_BOOKS'
     AND column_name = 'DESCRIPTION';

  IF v_nullable = 'N' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY description NULL';
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
    v_type VARCHAR2(30);
BEGIN
    SELECT data_type INTO v_type
      FROM user_tab_columns
     WHERE table_name = 'POSTS' AND column_name = 'CONTENT';

    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE posts ADD content_new CLOB';
        EXECUTE IMMEDIATE 'UPDATE posts SET content_new = TO_CLOB(content)';
        EXECUTE IMMEDIATE 'ALTER TABLE posts DROP COLUMN content';
        EXECUTE IMMEDIATE 'ALTER TABLE posts RENAME COLUMN content_new TO content';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
    v_type VARCHAR2(30);
BEGIN
    SELECT data_type INTO v_type
      FROM user_tab_columns
     WHERE table_name = 'POST_COMMENTS' AND column_name = 'CONTENT';

    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE post_comments ADD content_new CLOB';
        EXECUTE IMMEDIATE 'UPDATE post_comments SET content_new = TO_CLOB(content)';
        EXECUTE IMMEDIATE 'ALTER TABLE post_comments DROP COLUMN content';
        EXECUTE IMMEDIATE 'ALTER TABLE post_comments RENAME COLUMN content_new TO content';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
    v_type VARCHAR2(30);
BEGIN
    SELECT data_type INTO v_type
      FROM user_tab_columns
     WHERE table_name = 'RECOMMENDATION_BOOKS' AND column_name = 'DESCRIPTION';

    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books ADD description_new CLOB';
        EXECUTE IMMEDIATE 'UPDATE recommendation_books SET description_new = TO_CLOB(description)';
        EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books DROP COLUMN description';
        EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books RENAME COLUMN description_new TO description';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
  t NUMBER;
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO t FROM user_tables WHERE table_name = 'RECOMMENDATION_BOOKS';
  IF t > 0 THEN
    SELECT COUNT(*) INTO v_cnt
      FROM user_tab_columns
     WHERE table_name = 'RECOMMENDATION_BOOKS'
       AND column_name = 'SEARCH_KEYWORD';

    IF v_cnt = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books ADD (search_keyword VARCHAR2(500 CHAR))';
    END IF;
  END IF;
END;
/

-- =============================================================================
-- 2. 구 스키마 users 보정(role) + book_reviews (users FK — users 는 섹션 0 에서 생성)
-- =============================================================================

DECLARE
  u NUMBER;
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO u FROM user_tables WHERE table_name = 'USERS';
  IF u > 0 THEN
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
     WHERE table_name = 'USERS' AND column_name = 'ROLE';
    IF v_cnt = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE users ADD (role VARCHAR2(20 CHAR) DEFAULT ''USER'' NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_constraints
     WHERE table_name = 'USERS' AND constraint_name = 'CHK_USERS_ROLE';
    IF v_cnt = 0 THEN
      BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN (''USER'', ''COUNSELOR'', ''ADMIN''))';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE IN (-2260, -2261, -2275) THEN NULL; ELSE RAISE; END IF;
      END;
    END IF;
  END IF;
END;
/

DECLARE
  u NUMBER;
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO u FROM user_tables WHERE table_name = 'USERS';
  IF u = 0 THEN
    RAISE_APPLICATION_ERROR(-20901, 'USERS 없음: 스크립트 맨 위 섹션 0 실행 여부 확인');
  END IF;
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'BOOK_REVIEWS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE book_reviews (
        id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        user_id     NUMBER          NOT NULL,
        book_link   VARCHAR2(2000)  NOT NULL,
        book_title  VARCHAR2(500),
        rating      NUMBER(1)       NOT NULL,
        content     VARCHAR2(1000),
        created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_br_user    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT chk_br_rating CHECK (rating BETWEEN 1 AND 5),
        CONSTRAINT uq_br_user_book UNIQUE (user_id, book_link)
      )
    ]';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_br_book_link ON book_reviews(book_link)';
  END IF;
END;
/

-- =============================================================================
-- 2b. 샘플 시드 (김동주 data.sql 동일) — 관리자 MERGE + 공지/게시글(테이블 있을 때만)
--     관리자: admin@mindlink.com / 비밀번호 admin1234
-- =============================================================================

DECLARE
  u NUMBER;
BEGIN
  SELECT COUNT(*) INTO u FROM user_tables WHERE table_name = 'USERS';
  IF u > 0 THEN
    MERGE INTO users usr
    USING (SELECT 'admin@mindlink.com' AS email FROM dual) s
    ON (usr.email = s.email)
    WHEN NOT MATCHED THEN
      INSERT (name, email, password, role, created_at)
      VALUES (
        '관리자',
        'admin@mindlink.com',
        '$2a$10$cjwUlGVCVIxzYLVt7eP3XegA4dxbZtULyD5aPCUrnS.jfKkU3U23G',
        'ADMIN',
        SYSTIMESTAMP
      );
  END IF;
END;
/

DECLARE
  a NUMBER;
  b NUMBER;
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO a FROM user_tables WHERE table_name = 'POSTS';
  SELECT COUNT(*) INTO b FROM user_tables WHERE table_name = 'POST_COMMENTS';
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'NOTICES';
  IF a = 0 OR b = 0 OR c = 0 THEN
    NULL;
  ELSE
    DELETE FROM post_comments;
    DELETE FROM posts;
    DELETE FROM notices;

-- ── 공지사항 ──────────────────────────────────────────────────────────────────

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '중요',
  '마음이음 서비스 정식 오픈을 알립니다',
  '자가진단, AI 정서 케어, 맞춤 도서 추천, 상담소 찾기까지 마음 건강의 모든 것을 한 곳에서 이용하실 수 있습니다.',
  Q'^안녕하세요, 마음이음입니다.

마음이음 서비스가 정식 오픈하였습니다.
마음이음은 일상 속에서 자연스럽게 마음 건강을 돌볼 수 있도록 돕는 정서 케어 플랫폼입니다.

■ 주요 서비스 안내
  - 자가진단: PHQ-9(우울), GAD-7(불안), PSS-10(스트레스), CBI(번아웃) 4가지 검사를 무료로 이용하실 수 있습니다.
  - AI 정서 케어: 현재 기분을 짧게 입력하면 감정 분석 후 맞춤 케어를 제안합니다.
  - 맞춤 도서 추천: 진단 결과와 감정 상태를 기반으로 도움이 될 도서를 추천합니다.
  - 커뮤니티: 비슷한 고민을 가진 분들과 익명으로 이야기를 나눌 수 있습니다.
  - 상담소 찾기: 인근 심리상담센터 및 정신건강복지센터를 검색하고 예약할 수 있습니다.

■ 개인정보 보호
  모든 자가진단 결과와 개인 정보는 암호화되어 안전하게 보관됩니다.
  익명 커뮤니티 활동이 가능하며, 타인에게 진단 결과가 공개되지 않습니다.

마음이 힘들 때 혼자 버티지 마세요. 마음이음이 함께하겠습니다.^',
  SYSTIMESTAMP - INTERVAL '3' DAY
);

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '서비스',
  '자가진단 100% 활용하는 방법 안내',
  '4가지 자가진단 검사(우울·불안·스트레스·번아웃)를 주기적으로 받으면 마음 건강 변화 추이를 확인할 수 있습니다.',
  Q'^안녕하세요, 마음이음입니다.

마음이음의 자가진단 기능을 100% 활용하는 방법을 안내드립니다.

■ 제공 검사 종류
  - PHQ-9 (우울 척도): 지난 2주간의 우울 증상을 측정합니다. 5~9점 경증, 10~14점 중등도, 15점 이상 중등도-중증입니다.
  - GAD-7 (불안 척도): 일반화된 불안장애 증상을 측정합니다. 5~9점 경증, 10~14점 중등도, 15점 이상 중증입니다.
  - PSS-10 (스트레스 척도): 지난 한 달간의 스트레스 수준을 측정합니다. 14~26점 보통, 27점 이상 높음입니다.
  - CBI (번아웃 척도): 개인 번아웃과 업무 번아웃을 각각 측정합니다.

■ 효과적으로 사용하는 팁
  1. 2~4주 간격으로 정기적으로 받으세요. 변화 추이를 확인할 수 있습니다.
  2. 검사 결과는 "지금 이 순간"의 상태를 반영합니다. 기복이 있어도 괜찮습니다.
  3. 중등도 이상 결과가 지속된다면 전문 상담을 고려해보세요.
  4. 검사 후 맞춤 추천 페이지에서 도움이 될 활동과 도서를 확인하세요.

■ 주의 사항
  자가진단은 전문 의료 진단을 대체하지 않습니다.
  결과가 걱정된다면 정신건강 전문가 또는 상담사에게 도움을 받으시기 바랍니다.^',
  SYSTIMESTAMP - INTERVAL '8' DAY
);

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '서비스',
  '커뮤니티 이용 안내 및 건강한 소통 문화 만들기',
  '익명으로 안전하게 소통하는 커뮤니티입니다. 서로를 존중하는 건강한 이용 문화를 함께 만들어가요.',
  Q'^안녕하세요, 마음이음입니다.

마음이음 커뮤니티는 마음 건강에 관한 고민을 익명으로 나눌 수 있는 공간입니다.

■ 커뮤니티 이용 안내
  - 게시물은 익명으로 작성됩니다. 다른 사용자의 개인정보가 노출되지 않도록 주의해 주세요.
  - 카테고리: 스트레스, 우울, 불안, 인간관계, 일상·기타로 구분됩니다.
  - 부적절한 게시물은 신고 기능을 통해 제보해주시면 검토 후 처리합니다.

■ 건강한 소통을 위한 부탁
  1. 비슷한 어려움을 겪는 분들의 글에 따뜻한 댓글로 응원해주세요.
  2. 판단하거나 평가하는 댓글보다 공감과 위로의 말을 건네주세요.
  3. 전문적인 의학적 조언이나 진단은 삼가주세요. 전문가에게 연결해드리는 것이 더 도움이 됩니다.
  4. 위기 상황(자해·자살 위험)을 인지하면 즉시 자살예방상담전화(1393) 또는 정신건강위기상담전화(1577-0199)로 연락해주세요.

■ 위기 시 연락처
  - 자살예방상담전화: 1393 (24시간)
  - 정신건강위기상담전화: 1577-0199 (24시간)
  - 생명의전화: 1588-9191 (24시간)^',
  SYSTIMESTAMP - INTERVAL '15' DAY
);

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '서비스',
  '상담소 찾기 기능 개선 안내',
  '카드형 UI와 필터 검색으로 가까운 심리상담센터를 더 빠르게 찾아볼 수 있습니다.',
  Q'^안녕하세요, 마음이음입니다.

상담소 찾기 페이지가 새롭게 개선되었습니다.

■ 개선 내용
  - 카드형 디자인으로 센터 정보(위치·전화·영업시간·평점)를 한눈에 확인
  - 센터 유형별 필터링 (심리상담센터, 정신건강복지센터, 청소년상담복지센터 등)
  - 키워드 검색 (센터명, 지역, 전문 분야)
  - 예약 신청 기능: 원하는 센터를 선택해 방문 날짜·시간·유형을 입력하면 예약이 접수됩니다.

■ 무료 상담 안내
  지역 정신건강복지센터는 무료 또는 저비용으로 이용할 수 있습니다.
  경제적 부담 없이 전문가의 도움을 받으실 수 있으니 꼭 활용해보세요.

앞으로도 더 편리한 서비스를 위해 지속적으로 개선하겠습니다.^',
  SYSTIMESTAMP - INTERVAL '22' DAY
);

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '점검',
  '정기 시스템 점검 안내 (매월 둘째 주 화요일 02:00~04:00)',
  '서비스 안정성 향상을 위한 정기 점검이 매월 둘째 주 화요일 새벽 2시부터 4시까지 진행됩니다.',
  Q'^안녕하세요, 마음이음입니다.

서비스 안정성과 보안을 유지하기 위해 정기 점검을 진행합니다.

■ 점검 일정
  매월 둘째 주 화요일 02:00 ~ 04:00 (KST)

■ 점검 내용
  - 서버 보안 패치 및 업데이트
  - 데이터베이스 무결성 검증 및 백업
  - 성능 최적화 작업
  - 신규 기능 배포

■ 점검 중 서비스 상태
  점검 시간 동안에는 일부 기능 이용이 제한될 수 있습니다.
  긴급한 경우 정신건강위기상담전화(1577-0199, 24시간)를 이용해주세요.

이용에 불편을 드려 죄송합니다. 더 나은 서비스를 위한 작업임을 양해 부탁드립니다.^',
  SYSTIMESTAMP - INTERVAL '30' DAY
);

-- ── 커뮤니티 게시글 ──────────────────────────────────────────────────────────

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '숨고싶은날',
  '4-7-8 호흡법 써보신 분 계세요? 정말 효과 있더라고요',
  '불안이 심할 때 4-7-8 호흡법을 알게 됐는데, 코로 4초 들이마시고 7초 참고 8초 동안 입으로 내뱉는 방법이에요. 처음엔 7초 참는 게 힘들어서 짧게 시작했는데 지금은 익숙해졌어요. 잠들기 전이나 갑자기 불안해질 때 정말 도움이 됩니다. 저처럼 호흡으로 불안 다스려보신 분들 다른 방법도 알려주시면 좋겠어요!',
  '불안',
  31,
  SYSTIMESTAMP - INTERVAL '1' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '조용히버팀',
  '처음으로 심리상담 받고 왔어요 — 후기 공유합니다',
  '몇 달을 고민하다가 드디어 상담 받으러 갔어요. 솔직히 말하면 가기 전날 밤까지 취소하고 싶었는데, 막상 받아보니 생각보다 훨씬 편안했습니다. 상담사 선생님이 판단하지 않고 그냥 다 들어주셔서 처음으로 말하는 동안 울었어요. 비용이 걱정되는 분들은 지역 정신건강복지센터에서 무료로 이용할 수 있으니 꼭 알아보세요. 혼자 버티지 말고 도움 받는 거 절대 부끄러운 일 아닙니다.',
  '일상·기타',
  58,
  SYSTIMESTAMP - INTERVAL '2' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '새벽감성',
  '번아웃인지 그냥 게으른 건지 구별이 안 될 때',
  '요즘 아무것도 하기 싫고 예전엔 좋아하던 것들도 재미가 없어요. 의지력 문제라고 스스로를 탓하다가 마음이음에서 번아웃 검사(CBI)를 해봤는데 점수가 꽤 높게 나왔어요. 번아웃은 게으름이 아니라 에너지가 완전히 소진된 상태라는 걸 알게 됐고 조금 마음이 편해졌어요. 비슷한 분들 계시면 자가진단 한번 해보시는 걸 추천해요. 뭔가 이름을 붙여주는 게 도움이 되더라고요.',
  '스트레스',
  43,
  SYSTIMESTAMP - INTERVAL '3' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '마음연습중',
  '우울할 때 혼자 할 수 있는 것들 — 제가 해본 것들 모음',
  '우울한 날 저를 조금이라도 낫게 해준 것들을 모아봤어요. 거창한 건 아니고요. 1) 커튼 열기: 햇빛이 들어오면 조금 달라져요. 2) 5분만 걷기: 5분이 10분, 20분이 되는 경우가 많아요. 3) 차가운 물로 세수하기: 즉각적으로 각성됩니다. 4) 맛있는 것 하나 시켜먹기: 작은 즐거움이 중요해요. 5) 좋아하는 영상 틀어놓기: 혼자가 덜 느껴져요. 당장 나아지진 않더라도, 이렇게 하루를 버티는 것도 충분히 잘하고 있는 거예요.',
  '우울',
  76,
  SYSTIMESTAMP - INTERVAL '4' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '거리두기연습',
  '직장 내 감정 소모가 심한데 어떻게 경계를 긋나요?',
  '팀장님이 자꾸 사적인 감정을 업무에 섞어서 말씀하시는데 어떻게 대응해야 할지 모르겠어요. 직접적으로 말했다가 관계가 나빠질까봐 그냥 참고 있거든요. 그 결과 집에 오면 완전히 방전돼서 아무것도 못해요. 비슷한 경험 있으신 분들 어떻게 경계를 지으셨는지 궁금합니다. 상담 받으러 가야 하나 고민 중이에요.',
  '인간관계',
  29,
  SYSTIMESTAMP - INTERVAL '5' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '감사연습3주차',
  '감사 일기 3주 써보고 느낀 점 솔직 후기',
  '처음엔 반신반의로 시작했어요. 매일 감사한 일 3가지씩 적는 건데, 처음 일주일은 "오늘도 살아있다" "날씨가 나쁘지 않았다" 같은 거 적었어요. 근데 2주차부터 조금 달라지더라고요. 사소한 것들이 눈에 들어오기 시작했고, 아직 많이 바뀌진 않았지만 하루를 돌아보는 습관이 생긴 게 좋은 것 같아요. 같이 시작하실 분 있으면 댓글로 알려주세요!',
  '일상·기타',
  52,
  SYSTIMESTAMP - INTERVAL '6' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '조용한불안',
  'PHQ-9 중등도 나왔는데 바로 병원 가야 하나요?',
  '자가진단을 처음 해봤는데 우울 점수가 중등도로 나왔어요. 갑자기 무섭기도 하고 이게 맞는 건가 싶기도 하고요. 병원 가는 게 무서워서 일단 여기 물어봐요. 혹시 비슷한 점수 나오신 분들 어떻게 하셨나요? 상담센터랑 정신건강의학과 중에 어디가 더 나을지도 궁금합니다.',
  '우울',
  34,
  SYSTIMESTAMP - INTERVAL '7' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '명상초보자',
  '명상 6개월째 — 달라진 것과 달라지지 않은 것',
  '작년 이맘때부터 매일 아침 10분씩 명상을 시작했어요. 결론부터 말하면 인생이 극적으로 바뀌진 않았어요. 하지만 달라진 건 있어요. 불안이 생겼을 때 조금 더 빠르게 알아차리게 됐고, "이건 내 생각일 뿐이다"라고 거리를 두는 게 전보다 쉬워졌어요. 처음 시작하시는 분들 너무 큰 기대 갖지 마시고, 그냥 매일 조금씩 하는 것 자체가 목적이라고 생각하시면 오래 유지할 수 있어요.',
  '스트레스',
  47,
  SYSTIMESTAMP - INTERVAL '8' DAY
);

-- ── 댓글 ─────────────────────────────────────────────────────────────────────

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '따뜻한시선', '4-7-8 저도 써봤는데 정말 효과 있더라고요! 특히 잠들기 전에. 박스 호흡(4-4-4-4)도 한번 해보세요 :)', SYSTIMESTAMP - INTERVAL '20' HOUR
FROM posts WHERE title = '4-7-8 호흡법 써보신 분 계세요? 정말 효과 있더라고요' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '같은마음', '저도 비슷해요. 호흡할 때 손을 배에 올려두면 더 집중이 잘 됐어요. 공유해주셔서 감사합니다.', SYSTIMESTAMP - INTERVAL '15' HOUR
FROM posts WHERE title = '4-7-8 호흡법 써보신 분 계세요? 정말 효과 있더라고요' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '용기내서', '저도 몇 달 고민하다 작년에 처음 갔는데 진짜 잘한 선택이었어요. 응원합니다!', SYSTIMESTAMP - INTERVAL '40' HOUR
FROM posts WHERE title = '처음으로 심리상담 받고 왔어요 — 후기 공유합니다' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '고민중인사람', '정신건강복지센터 무료인 거 몰랐어요. 알려주셔서 감사합니다. 저도 알아봐야겠어요.', SYSTIMESTAMP - INTERVAL '30' HOUR
FROM posts WHERE title = '처음으로 심리상담 받고 왔어요 — 후기 공유합니다' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '나도번아웃', '이름 붙여주는 게 도움이 된다는 말 너무 공감해요. 나만 이상한 게 아니구나 싶어서 안도가 됐어요.', SYSTIMESTAMP - INTERVAL '55' HOUR
FROM posts WHERE title = '번아웃인지 그냥 게으른 건지 구별이 안 될 때' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '따뜻한위로', '커튼 열기부터 해볼게요. 이렇게 작은 것부터 알려주셔서 감사해요. 오늘 하루도 수고하셨어요.', SYSTIMESTAMP - INTERVAL '70' HOUR
FROM posts WHERE title = '우울할 때 혼자 할 수 있는 것들 — 제가 해본 것들 모음' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '공감해요', '직장 내 경계 설정 정말 어렵죠. 저는 "지금 좀 소화할 시간이 필요해요"라는 말을 쓰기 시작했는데 조금 도움이 됐어요.', SYSTIMESTAMP - INTERVAL '90' HOUR
FROM posts WHERE title = '직장 내 감정 소모가 심한데 어떻게 경계를 긋나요?' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '함께해요', '저도 같이 시작할게요! 오늘부터 감사 일기 도전합니다 :)', SYSTIMESTAMP - INTERVAL '100' HOUR
FROM posts WHERE title = '감사 일기 3주 써보고 느낀 점 솔직 후기' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '경험공유', '중등도 나왔을 때 저는 상담센터 먼저 갔어요. 처음엔 상담이 좀 더 접근하기 쉬운 것 같더라고요. 필요하면 그분이 병원 연계도 해주셨어요.', SYSTIMESTAMP - INTERVAL '120' HOUR
FROM posts WHERE title = 'PHQ-9 중등도 나왔는데 바로 병원 가야 하나요?' AND ROWNUM = 1;

  END IF;
END;
/

-- =============================================================================
-- 3. recommendation_books — 전량 삭제 후 교보링크 세트 재적재
--    (네이버 캐시 ISBN 행까지 모두 지움. 캐시 유지가 필요하면 맨 아래 주석 시드 사용)
-- =============================================================================

DECLARE
    v_sql VARCHAR2(4000);
BEGIN
    FOR c IN (
        SELECT constraint_name
          FROM user_constraints
         WHERE table_name = 'RECOMMENDATION_BOOKS'
           AND constraint_type = 'C'
           AND UPPER(search_condition_vc) LIKE '%EMOTION%'
    ) LOOP
        v_sql := 'ALTER TABLE recommendation_books DROP CONSTRAINT ' || c.constraint_name;
        EXECUTE IMMEDIATE v_sql;
    END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[ALTER TABLE recommendation_books ADD CONSTRAINT chk_recommendation_books_emotion
    CHECK (emotion IN ('DEPRESSION', 'STRESS', 'ANXIETY', 'LETHARGY', 'RELATIONSHIP', 'NORMAL'))]';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'RECOMMENDATION_BOOKS';
  IF v_cnt = 0 THEN RETURN; END IF;

  EXECUTE IMMEDIATE 'DELETE FROM recommendation_books';

  EXECUTE IMMEDIATE q'[INSERT INTO recommendation_books (emotion, title, author, publisher, link, image, description)
  SELECT 'STRESS', '스트레스(STRESS)', '로버트 새폴스키', '사이언스북스', 'https://product.kyobobook.co.kr/detail/S000001290666', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788983712325.jpg', '과학적 시각으로 스트레스의 본질을 파고드는 심층 분석서' FROM dual
  UNION ALL SELECT 'STRESS', '스트레스는 어떻게 삶을 이롭게 하는가', '우르스 빌만', '심심', 'https://product.kyobobook.co.kr/detail/S000001744823', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156757085.jpg', '인간의 진화와 발전에 커다란 영향을 미친 스트레스 이야기' FROM dual
  UNION ALL SELECT 'STRESS', '스트레스와 트라우마, 치유할 수 있다', '데이빗 버셀리', '오랜 기억', 'https://product.kyobobook.co.kr/detail/S000001971552', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791196076931.jpg', NULL FROM dual
  UNION ALL SELECT 'ANXIETY', '불안 끄기 연습', '오언 오케인', '웅진지식하우스', 'https://product.kyobobook.co.kr/detail/S000219997725', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788901299860.jpg', '불안을 없애려 할수록 더 불안해지는 사람들을 위한 심리 처방전' FROM dual
  UNION ALL SELECT 'DEPRESSION', '우울할 땐 뇌 과학', '앨릭스 코브', '심심', 'https://product.kyobobook.co.kr/detail/S000001744837', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156757344.jpg', '우울감을 뇌 과학으로 이해하고 삶의 변화를 이끄는 실천 안내서' FROM dual
  UNION ALL SELECT 'DEPRESSION', '자존감 수업', '윤홍균', '심플라이프', 'https://product.kyobobook.co.kr/detail/S000001891815', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791186757093.jpg', '마음의 길을 밝혀주는 현실적인 자존감 이정표' FROM dual
  UNION ALL SELECT 'DEPRESSION', '홀로서기 심리학', '라라 E. 필딩', '메이븐', 'https://product.kyobobook.co.kr/detail/S000001941412', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190538206.jpg', '흔들리는 마음을 다독이며 스스로 단단하게 설 수 있도록 이끄는 심리 안내서' FROM dual
  UNION ALL SELECT 'DEPRESSION', '아무것도 하지 않으면 아무 일도 일어나지 않는다', '기시미 이치로', '살림', 'https://product.kyobobook.co.kr/detail/S000000722112', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788952235107.jpg', '생각만 하던 나를 행동으로 이끄는 실천의 심리학' FROM dual
  UNION ALL SELECT 'DEPRESSION', '당신이 옳다', '정혜신', '해냄출판사', 'https://product.kyobobook.co.kr/detail/S000001026048', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788965746669.jpg', '상대와 나를 이해하는 진정한 공감의 지혜를 전하는 책' FROM dual
  UNION ALL SELECT 'ANXIETY', '불안', '알랭 드 보통', '은행나무', 'https://product.kyobobook.co.kr/detail/S000000828225', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788956605593.jpg', '불안의 근원을 찾아 객관적 통찰과 깊은 위안을 주는 책' FROM dual
  UNION ALL SELECT 'ANXIETY', '과거가 남긴 우울 미래가 보낸 불안', '김아라', '유노북스', 'https://product.kyobobook.co.kr/detail/S000061451536', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192300214.jpg', '불안과 우울을 넘어 현재에 집중하도록 돕는 다정한 마음 지침서' FROM dual
  UNION ALL SELECT 'ANXIETY', '불안을 알면 흔들리지 않는다', '키렌 슈나크', '오픈도어북스', 'https://product.kyobobook.co.kr/detail/S000218204279', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791173741975.jpg', '불안의 본질을 이해하고 흔들림 속에서도 단단함을 찾는 안내서' FROM dual
  UNION ALL SELECT 'ANXIETY', '당신의 불안은 죄가 없다', '웬디 스즈키', '21세기북스', 'https://product.kyobobook.co.kr/detail/S000213834268', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791171176670.jpg', NULL FROM dual
  UNION ALL SELECT 'RELATIONSHIP', '나는 왜 네 말이 힘들까', '박재연', '한빛라이프', 'https://product.kyobobook.co.kr/detail/S000001944783', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190846011.jpg', '관계 속 상처를 보듬고 건강한 대화를 이끄는 통찰의 안내서' FROM dual
  UNION ALL SELECT 'RELATIONSHIP', '말센스', '셀레스트 헤들리', '스몰빅라이프', 'https://product.kyobobook.co.kr/detail/S000001898255', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187165460.jpg', '대화의 본질을 깨닫고 관계를 변화시키는 안내서' FROM dual
  UNION ALL SELECT 'RELATIONSHIP', '나는 왜 남들보다 쉽게 지칠까', '최재훈', '서스테인', 'https://product.kyobobook.co.kr/detail/S000213675097', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193388075.jpg', '쉽게 지치는 나를 이해하고 보듬어주는 다정한 안내서' FROM dual
  UNION ALL SELECT 'RELATIONSHIP', '데일 카네기 인간관계론', '데일 카네기', '현대지성', 'https://product.kyobobook.co.kr/detail/S000001897788', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187142560.jpg', NULL FROM dual
  UNION ALL SELECT 'RELATIONSHIP', '미움받을 용기', '기시미 이치로, 고가 후미타케', '인플루엔셜', 'https://product.kyobobook.co.kr/detail/S000200555616', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791168340770.jpg', '관계 속에서 나를 찾고 행복할 용기를 주는 아들러 심리학 안내서' FROM dual
  UNION ALL SELECT 'LETHARGY', '나는 왜 무기력을 되풀이하는가', '에리히 프롬', '나무생각', 'https://product.kyobobook.co.kr/detail/S000001890530', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791186688519.jpg', NULL FROM dual
  UNION ALL SELECT 'LETHARGY', '어느 날 갑자기 무기력이 찾아왔다', '클라우스 베른하르트', '동녘라이프', 'https://product.kyobobook.co.kr/detail/S000001449403', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788990514776.jpg', NULL FROM dual
  UNION ALL SELECT 'LETHARGY', '무기력이 무기력해지도록', '한창수', '알에이치코리아', 'https://product.kyobobook.co.kr/detail/S000000479280', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925579863.jpg', '무기력의 실체를 이해하고 극복의 길을 제시하는 전문적인 안내서' FROM dual
  UNION ALL SELECT 'LETHARGY', '지쳤거나 좋아하는 게 없거나', '글배우', '강한별', 'https://product.kyobobook.co.kr/detail/S000001986809', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791197472558.jpg', '지친 마음을 따뜻하게 위로하고 다시 일어설 용기를 주는 에세이' FROM dual]';

  COMMIT;
END;
/

-- =============================================================================
-- [선택] 가벼운 시드 — ISBN이 NULL인 수동 행만 지우고 감정별 5권×4감정(20권) 삽입
--       네이버 캐시(ISBN 있음)는 유지하고 싶을 때: 아래 블록 주석을 해제하고,
--       위 섹션 3 전체(제약 재설정·DELETE·INSERT …)는 실행하지 말 것.
-- =============================================================================
/*
DELETE FROM recommendation_books WHERE isbn IS NULL;

INSERT ALL
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '죽고 싶지만 떡볶이는 먹고 싶어', '백세희', '흔', NULL, NULL, '우울감을 솔직하게 풀어낸 에세이')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '나는 나로 살기로 했다', '김수현', '마음의숲', NULL, NULL, '자기 자신을 사랑하는 법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '감정의 발견', '마크 브래킷', '북라이프', NULL, NULL, '감정을 이해하고 다루는 방법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '우울할 땐 뇌과학', '알렉스 코브', '심심', NULL, NULL, '뇌과학으로 보는 우울증 극복법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '괜찮지 않아도 괜찮아', '최명기', '더퀘스트', NULL, NULL, '있는 그대로의 나를 받아들이는 심리 에세이')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '마음챙김', '마크 윌리엄스', '불광출판사', NULL, NULL, '스트레스 해소를 위한 마음챙김')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '지금 이 순간을 살아라', '에크하르트 톨레', '양문', NULL, NULL, '현재에 집중하는 삶')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '번아웃 사회', '한병철', '문학과지성사', NULL, NULL, '현대 사회의 피로감을 분석')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '쉬어도 피곤한 사람들', '박용철', '21세기북스', NULL, NULL, '번아웃에서 벗어나는 회복 전략')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '번아웃', '에밀리 나고스키', '해나무', NULL, NULL, '완벽주의에서 벗어나 진짜 쉬는 법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '불안', '알랭 드 보통', '은행나무', NULL, NULL, '불안의 본질을 탐구')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '오늘도 불안한 너에게', '박진영', '시공사', NULL, NULL, '불안을 극복하는 실천법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '명상록', '마르쿠스 아우렐리우스', '현대지성', NULL, NULL, '내면의 평화를 위한 철학적 성찰')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '걱정 끄기 연습', '쑤언 수치', '유노북스', NULL, NULL, '걱정을 줄이는 심리 기법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '불안해도 괜찮아', '클라우스 베른하르트', '갈매나무', NULL, NULL, '불안 장애를 스스로 극복하는 인지 훈련법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '아주 작은 습관의 힘', '제임스 클리어', '비즈니스북스', NULL, NULL, '작은 습관으로 큰 변화를')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '미라클 모닝', '할 엘로드', '한빛비즈', NULL, NULL, '아침을 바꾸면 인생이 바뀐다')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '그릿', '앤절라 더크워스', '비즈니스북스', NULL, NULL, '끝까지 해내는 힘의 비밀')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '내가 확실히 알고 있는 것들', '오프라 윈프리', '북하우스', NULL, NULL, '삶을 다시 시작하게 해주는 이야기')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '게으름에 대한 찬양', '버트런드 러셀', '사회평론', NULL, NULL, '진정한 휴식과 활력을 되찾는 철학적 에세이')
SELECT 1 FROM DUAL;

COMMIT;
*/
