-- =============================================================================
-- Mind-Link · Oracle 통합 스크립트 (한 파일)
-- 실행 계정: APP_USER (예: APP_USER / AppUser1234)
--
-- 전제: APP_USER 로 접속. 빈 스키마여도 섹션 0이 users·posts·공지 등 기본 테이블을 만듭니다.
--       (recommendation_books 만 Hibernate 등으로 이미 있을 때도 동작하도록 ALTER 는 조건부)
--
-- 구성
--   0) 기본 테이블 생성(없을 때만) — LoginCommunity.md §5 와 동일 순서
--   1) 스키마 보정 — 문자 길이, CLOB, recommendation_books.search_keyword (테이블 있을 때만 ALTER)
--   2) users role 보정(구 스키마) + book_reviews (users 존재 시에만 생성)
--   2b) 샘플 데이터 — 관리자 MERGE + 공지·게시글(해당 테이블이 모두 있을 때만)
--   3) recommendation_books 데이터 적재 (전량 재적재, 교보링크 세트)
--
-- 자가진단(김지훈): 본 파일 실행 후 @sql/ASSESSMENT_SEED.sql 을 별도 실행하세요.
-- 상담 예약(윤아연): 섹션 0에 bookings 테이블 포함 (Hibernate ddl-auto=none)
--
-- 데이터만 다시 넣고 싶다면: 섹션 3만 별도 복사해 실행해도 됨(전제 조건 동일).
-- 가벼운 20권 시드(수동 ISBN NULL 행만 교체)는 파일 맨 아래 주석 블록 참고.
-- =============================================================================

ALTER SESSION SET NLS_LENGTH_SEMANTICS=CHAR;

-- =============================================================================
-- 0. 기본 테이블 (없을 때만) — ddl-auto=none 이고 앱을 안 돌린 DB용
-- =============================================================================

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'USERS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE users (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        VARCHAR2(50 CHAR)  NOT NULL,
        email       VARCHAR2(100 CHAR) NOT NULL,
        password    VARCHAR2(255 CHAR) NOT NULL,
        role        VARCHAR2(20 CHAR)  DEFAULT 'USER' NOT NULL,
        created_at  TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT uq_users_email UNIQUE (email),
        CONSTRAINT chk_users_role CHECK (role IN ('USER', 'COUNSELOR', 'ADMIN'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POSTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE posts (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        author      VARCHAR2(50 CHAR)  NOT NULL,
        title       VARCHAR2(200 CHAR) NOT NULL,
        content     CLOB                 NOT NULL,
        category    VARCHAR2(30 CHAR)   NOT NULL,
        likes       NUMBER(10)          DEFAULT 0 NOT NULL,
        created_at  TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POST_COMMENTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE post_comments (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        post_id     NUMBER       NOT NULL,
        author      VARCHAR2(50 CHAR) NOT NULL,
        content     CLOB                NOT NULL,
        created_at  TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'REPORTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE reports (
        id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        reporter_id  NUMBER      NOT NULL,
        target_type  VARCHAR2(10 CHAR) NOT NULL,
        target_id    NUMBER      NOT NULL,
        reason       CLOB        NOT NULL,
        created_at   TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users(id),
        CONSTRAINT chk_reports_target_type CHECK (target_type IN ('POST', 'COMMENT'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'NOTICES';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE notices (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category    VARCHAR2(30 CHAR)  NOT NULL,
        title       VARCHAR2(200 CHAR) NOT NULL,
        summary     VARCHAR2(500 CHAR) NOT NULL,
        content     CLOB                 NOT NULL,
        created_at  TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'ATTACHMENTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE attachments (
        id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_file_name VARCHAR2(255 CHAR) NOT NULL,
        stored_file_name    VARCHAR2(255 CHAR) NOT NULL,
        file_url            VARCHAR2(500 CHAR) NOT NULL,
        file_type           VARCHAR2(10 CHAR)  NOT NULL,
        file_size           NUMBER(20)         DEFAULT 0 NOT NULL,
        target_type         VARCHAR2(10 CHAR)  NOT NULL,
        target_id           NUMBER             NOT NULL,
        created_at          TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT chk_attachments_file_type CHECK (file_type IN ('IMAGE', 'VIDEO', 'LINK')),
        CONSTRAINT chk_attachments_target_type CHECK (target_type IN ('POST', 'COMMENT'))
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'BOOKINGS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE bookings (
        id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        center_name     VARCHAR2(200 CHAR) NOT NULL,
        center_title    VARCHAR2(100 CHAR),
        center_phone    VARCHAR2(30 CHAR),
        center_address  VARCHAR2(300 CHAR),
        user_id         NUMBER,
        name            VARCHAR2(50 CHAR)  NOT NULL,
        phone           VARCHAR2(30 CHAR)  NOT NULL,
        email           VARCHAR2(100 CHAR) NOT NULL,
        booking_date    DATE               NOT NULL,
        booking_time    VARCHAR2(8 CHAR)   NOT NULL,
        type            VARCHAR2(50 CHAR),
        memo            CLOB,
        status          VARCHAR2(20 CHAR)  DEFAULT 'REQUESTED' NOT NULL,
        created_at      TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id),
        CONSTRAINT chk_bookings_status CHECK (status IN ('REQUESTED', 'CONFIRMED', 'CANCELLED'))
      )
    ]';
  END IF;

  -- 자가진단 결과 이력 (관리자/상담사 뷰에서 유저 상태 조회용)
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'ASSESSMENT_RESULTS';
  IF c = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE assessment_results (
        id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id      NUMBER,
        type_key     VARCHAR2(50 CHAR)  NOT NULL,
        type_name    VARCHAR2(100 CHAR) NOT NULL,
        score        NUMBER(10)         DEFAULT 0 NOT NULL,
        result_level VARCHAR2(60 CHAR)  NOT NULL,
        high_risk    NUMBER(1)          DEFAULT 0 NOT NULL,
        created_at   TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_assessment_results_user FOREIGN KEY (user_id) REFERENCES users(id),
        CONSTRAINT chk_assessment_results_high_risk CHECK (high_risk IN (0, 1))
      )
    ]';
  END IF;
END;
/

-- =============================================================================
-- 1. 스키마 보정 (문자 길이 여유 + CLOB + search_keyword)
-- =============================================================================

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POSTS';
  IF c > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE posts MODIFY (author VARCHAR2(200 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE posts MODIFY (title VARCHAR2(1000 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE posts MODIFY (category VARCHAR2(200 CHAR))';
  END IF;
END;
/

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'POST_COMMENTS';
  IF c > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE post_comments MODIFY (author VARCHAR2(200 CHAR))';
  END IF;
END;
/

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'RECOMMENDATION_BOOKS';
  IF c > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (title VARCHAR2(1000 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (author VARCHAR2(500 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (publisher VARCHAR2(500 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (link VARCHAR2(2000 CHAR))';
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY (image VARCHAR2(2000 CHAR))';
  END IF;
END;
/

DECLARE
  v_nullable VARCHAR2(1);
BEGIN
  SELECT nullable INTO v_nullable
    FROM user_tab_columns
   WHERE table_name = 'RECOMMENDATION_BOOKS'
     AND column_name = 'DESCRIPTION';

  IF v_nullable = 'N' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY description NULL';
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
    v_type VARCHAR2(30);
BEGIN
    SELECT data_type INTO v_type
      FROM user_tab_columns
     WHERE table_name = 'POSTS' AND column_name = 'CONTENT';

    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE posts ADD content_new CLOB';
        EXECUTE IMMEDIATE 'UPDATE posts SET content_new = TO_CLOB(content)';
        EXECUTE IMMEDIATE 'ALTER TABLE posts DROP COLUMN content';
        EXECUTE IMMEDIATE 'ALTER TABLE posts RENAME COLUMN content_new TO content';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
    v_type VARCHAR2(30);
BEGIN
    SELECT data_type INTO v_type
      FROM user_tab_columns
     WHERE table_name = 'POST_COMMENTS' AND column_name = 'CONTENT';

    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE post_comments ADD content_new CLOB';
        EXECUTE IMMEDIATE 'UPDATE post_comments SET content_new = TO_CLOB(content)';
        EXECUTE IMMEDIATE 'ALTER TABLE post_comments DROP COLUMN content';
        EXECUTE IMMEDIATE 'ALTER TABLE post_comments RENAME COLUMN content_new TO content';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
    v_type VARCHAR2(30);
BEGIN
    SELECT data_type INTO v_type
      FROM user_tab_columns
     WHERE table_name = 'RECOMMENDATION_BOOKS' AND column_name = 'DESCRIPTION';

    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books ADD description_new CLOB';
        EXECUTE IMMEDIATE 'UPDATE recommendation_books SET description_new = TO_CLOB(description)';
        EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books DROP COLUMN description';
        EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books RENAME COLUMN description_new TO description';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
  t NUMBER;
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO t FROM user_tables WHERE table_name = 'RECOMMENDATION_BOOKS';
  IF t > 0 THEN
    SELECT COUNT(*) INTO v_cnt
      FROM user_tab_columns
     WHERE table_name = 'RECOMMENDATION_BOOKS'
       AND column_name = 'SEARCH_KEYWORD';

    IF v_cnt = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books ADD (search_keyword VARCHAR2(500 CHAR))';
    END IF;
  END IF;
END;
/

-- =============================================================================
-- 2. 구 스키마 users 보정(role) + book_reviews (users FK — users 는 섹션 0 에서 생성)
-- =============================================================================

DECLARE
  u NUMBER;
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO u FROM user_tables WHERE table_name = 'USERS';
  IF u > 0 THEN
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
     WHERE table_name = 'USERS' AND column_name = 'ROLE';
    IF v_cnt = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE users ADD (role VARCHAR2(20 CHAR) DEFAULT ''USER'' NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_constraints
     WHERE table_name = 'USERS' AND constraint_name = 'CHK_USERS_ROLE';
    IF v_cnt = 0 THEN
      BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN (''USER'', ''COUNSELOR'', ''ADMIN''))';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE IN (-2260, -2261, -2275) THEN NULL; ELSE RAISE; END IF;
      END;
    END IF;
  END IF;
END;
/

DECLARE
  u NUMBER;
BEGIN
  SELECT COUNT(*) INTO u FROM user_tables WHERE table_name = 'USERS';
  IF u = 0 THEN
    RAISE_APPLICATION_ERROR(-20901, 'USERS 없음: 스크립트 맨 위 섹션 0 실행 여부 확인');
  END IF;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE book_reviews CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;
  EXECUTE IMMEDIATE q'[
    CREATE TABLE book_reviews (
      id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      user_id     NUMBER          NOT NULL,
      book_link   VARCHAR2(2000)  NOT NULL,
      book_title  VARCHAR2(500),
      rating      NUMBER(1)       NOT NULL,
      content     VARCHAR2(1000),
      created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_br_user    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      CONSTRAINT chk_br_rating CHECK (rating BETWEEN 1 AND 5),
      CONSTRAINT uq_br_user_book UNIQUE (user_id, book_link)
    )
  ]';
  EXECUTE IMMEDIATE 'CREATE INDEX idx_br_book_link ON book_reviews(book_link)';
END;
/

-- =============================================================================
-- 2b. 샘플 시드 (김동주 data.sql 동일) — 관리자 MERGE + 공지/게시글(테이블 있을 때만)
--     관리자: admin@mindlink.com / 비밀번호 admin1234
-- =============================================================================

DECLARE
  u NUMBER;
BEGIN
  SELECT COUNT(*) INTO u FROM user_tables WHERE table_name = 'USERS';
  IF u > 0 THEN
    MERGE INTO users usr
    USING (SELECT 'admin@mindlink.com' AS email FROM dual) s
    ON (usr.email = s.email)
    WHEN NOT MATCHED THEN
      INSERT (name, email, password, role, created_at)
      VALUES (
        '관리자',
        'admin@mindlink.com',
        '$2a$10$cjwUlGVCVIxzYLVt7eP3XegA4dxbZtULyD5aPCUrnS.jfKkU3U23G',
        'ADMIN',
        SYSTIMESTAMP
      );
  END IF;
END;
/

DECLARE
  a NUMBER;
  b NUMBER;
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO a FROM user_tables WHERE table_name = 'POSTS';
  SELECT COUNT(*) INTO b FROM user_tables WHERE table_name = 'POST_COMMENTS';
  SELECT COUNT(*) INTO c FROM user_tables WHERE table_name = 'NOTICES';
  IF a = 0 OR b = 0 OR c = 0 THEN
    NULL;
  ELSE
    DELETE FROM post_comments;
    DELETE FROM posts;
    DELETE FROM notices;

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '중요',
  'AI 기반 정서 케어 베타 오픈 안내',
  'AI가 감정을 분석하고 단계별 케어를 제공하는 새로운 서비스가 베타 오픈되었습니다.',
  Q'^안녕하세요, 마음이음입니다.

많은 분들이 기다려주신 AI 기반 정서 케어 서비스가 베타 오픈되었습니다.
AI가 사용자의 메시지를 분석해 감정 상태와 위험도를 판단하고, 단계별로 맞춤 케어를 제공합니다.

■ 주요 기능
  - 실시간 감정 분석 및 위험도 단계 제시
  - 위험도에 따른 맞춤형 추천 (호흡법, 활동, 전문 상담 연계)
  - 고위험 상황에서 긴급 연락처 자동 안내

■ 이용 방법
  상단의 AI 정서 케어 메뉴에서 바로 이용하실 수 있습니다.

베타 기간 동안 발견되는 개선점은 지속적으로 반영하겠습니다. 많은 관심과 의견 부탁드립니다.^',
  SYSTIMESTAMP - INTERVAL '9' DAY
);

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '서비스',
  '상담소 찾기 기능이 새롭게 개편되었습니다',
  '지도 기반의 보기 좋은 카드 형태로 상담 센터를 더 빠르게 찾아볼 수 있습니다.',
  Q'^안녕하세요, 마음이음입니다.

상담소 찾기 페이지가 새롭게 단장했습니다.

■ 개편 내용
  - 가로형 카드 디자인 (썸네일 + 평점/거리/영업상태 + 위치/시간/전화)
  - 센터 유형별 필터링 (심리상담센터, 정신건강복지센터 등)
  - 키워드 검색 (센터명, 지역, 전문 분야)

앞으로도 더 편리한 사용 경험을 제공하기 위해 계속해서 개선해 나가겠습니다.^',
  SYSTIMESTAMP - INTERVAL '17' DAY
);

INSERT INTO notices (category, title, summary, content, created_at)
VALUES (
  '점검',
  '정기 시스템 점검 안내',
  '매월 둘째 주 화요일 오전 2시~4시 정기 점검이 진행됩니다.',
  Q'^안녕하세요, 마음이음입니다.

서비스 안정성을 높이기 위해 정기 점검을 진행합니다.

■ 점검 일정
  매월 둘째 주 화요일 02:00 ~ 04:00 (KST)

■ 점검 내용
  - 인프라 보안 패치
  - 데이터베이스 백업 및 무결성 점검
  - 신규 기능 배포

점검 시간 동안에는 서비스 이용이 일시적으로 제한될 수 있습니다.^',
  SYSTIMESTAMP - INTERVAL '31' DAY
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '익명123',
  '불안할 때 도움이 되는 호흡법 공유합니다',
  '최근 불안감이 심할 때 4-7-8 호흡법을 알게 됐어요. 4초 들이마시고, 7초 참고, 8초 내뱉기. 정말 도움이 되더라고요. 특히 잠들기 전이나 급하게 불안해질 때 효과적이었어요. 여러분도 한번 시도해보세요!',
  '스트레스 관리',
  24,
  SYSTIMESTAMP
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '힐링중',
  '오늘 처음으로 상담을 받았어요',
  '용기내서 전문 상담을 받았는데, 생각보다 훨씬 편안했습니다. 혼자 고민하지 말고 도움을 받는 게 중요한 것 같아요. 처음엔 두려웠지만 이제는 정말 잘한 선택이라고 생각합니다.',
  '경험 공유',
  45,
  SYSTIMESTAMP
);

INSERT INTO posts (author, title, content, category, likes, created_at)
VALUES (
  '새출발',
  '감사 일기 30일 챌린지 같이 하실 분!',
  '매일 감사한 일 3가지씩 기록하는 챌린지 시작합니다. 함께 하실 분 있으면 댓글 남겨주세요 :) 작은 것에도 감사하는 마음을 가지면 삶이 달라진다고 하더라고요.',
  '함께 해요',
  38,
  SYSTIMESTAMP
);

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '응원해요', '좋은 정보 감사합니다! 저도 한번 시도해볼게요.', SYSTIMESTAMP
FROM posts WHERE title = '불안할 때 도움이 되는 호흡법 공유합니다' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '함께해요', '정말 도움이 되는 글이네요. 저도 비슷한 경험이 있어서 공감됩니다.', SYSTIMESTAMP
FROM posts WHERE title = '불안할 때 도움이 되는 호흡법 공유합니다' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '용기있어요', '대단하세요! 저도 용기 내볼게요.', SYSTIMESTAMP
FROM posts WHERE title = '오늘 처음으로 상담을 받았어요' AND ROWNUM = 1;

INSERT INTO post_comments (post_id, author, content, created_at)
SELECT id, '참여할게요', '저도 같이 해요! 화이팅!', SYSTIMESTAMP
FROM posts WHERE title = '감사 일기 30일 챌린지 같이 하실 분!' AND ROWNUM = 1;

  END IF;
END;
/

-- =============================================================================
-- 3. recommendation_books — 전량 삭제 후 교보링크 세트 재적재
--    (네이버 캐시 ISBN 행까지 모두 지움. 캐시 유지가 필요하면 맨 아래 주석 시드 사용)
-- =============================================================================

DECLARE
    v_sql VARCHAR2(4000);
BEGIN
    FOR c IN (
        SELECT constraint_name
          FROM user_constraints
         WHERE table_name = 'RECOMMENDATION_BOOKS'
           AND constraint_type = 'C'
           AND UPPER(search_condition_vc) LIKE '%EMOTION%'
    ) LOOP
        v_sql := 'ALTER TABLE recommendation_books DROP CONSTRAINT ' || c.constraint_name;
        EXECUTE IMMEDIATE v_sql;
    END LOOP;
END;
/

ALTER TABLE recommendation_books ADD CONSTRAINT chk_recommendation_books_emotion
CHECK (emotion IN ('DEPRESSION', 'STRESS', 'ANXIETY', 'LETHARGY', 'RELATIONSHIP', 'NORMAL'));

DECLARE
  v_nullable VARCHAR2(1);
BEGIN
  SELECT nullable INTO v_nullable
    FROM user_tab_columns
   WHERE table_name = 'RECOMMENDATION_BOOKS'
     AND column_name = 'DESCRIPTION';

  IF v_nullable = 'N' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE recommendation_books MODIFY description NULL';
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
END;
/

DELETE FROM recommendation_books;

INSERT INTO recommendation_books (emotion, title, author, publisher, link, image, description)
SELECT 'STRESS', '스트레스(STRESS)', '로버트 새폴스키', '사이언스북스', 'https://product.kyobobook.co.kr/detail/S000001290666', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788983712325.jpg', '과학적 시각으로 스트레스의 본질을 파고드는 심층 분석서' FROM dual
UNION ALL SELECT 'STRESS', '스트레스는 어떻게 삶을 이롭게 하는가', '우르스 빌만', '심심', 'https://product.kyobobook.co.kr/detail/S000001744823', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156757085.jpg', '인간의 진화와 발전에 커다란 영향을 미친 스트레스 이야기' FROM dual
UNION ALL SELECT 'STRESS', '스트레스와 트라우마, 치유할 수 있다', '데이빗 버셀리', '오랜 기억', 'https://product.kyobobook.co.kr/detail/S000001971552', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791196076931.jpg', NULL FROM dual
UNION ALL SELECT 'ANXIETY', '불안 끄기 연습', '오언 오케인', '웅진지식하우스', 'https://product.kyobobook.co.kr/detail/S000219997725', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788901299860.jpg', '불안을 없애려 할수록 더 불안해지는 사람들을 위한 심리 처방전' FROM dual
UNION ALL SELECT 'DEPRESSION', '우울할 땐 뇌 과학', '앨릭스 코브', '심심', 'https://product.kyobobook.co.kr/detail/S000001744837', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791156757344.jpg', '우울감을 뇌 과학으로 이해하고 삶의 변화를 이끄는 실천 안내서' FROM dual
UNION ALL SELECT 'DEPRESSION', '자존감 수업', '윤홍균', '심플라이프', 'https://product.kyobobook.co.kr/detail/S000001891815', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791186757093.jpg', '마음의 길을 밝혀주는 현실적인 자존감 이정표' FROM dual
UNION ALL SELECT 'DEPRESSION', '홀로서기 심리학', '라라 E. 필딩', '메이븐', 'https://product.kyobobook.co.kr/detail/S000001941412', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190538206.jpg', '흔들리는 마음을 다독이며 스스로 단단하게 설 수 있도록 이끄는 심리 안내서' FROM dual
UNION ALL SELECT 'DEPRESSION', '아무것도 하지 않으면 아무 일도 일어나지 않는다', '기시미 이치로', '살림', 'https://product.kyobobook.co.kr/detail/S000000722112', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788952235107.jpg', '생각만 하던 나를 행동으로 이끄는 실천의 심리학' FROM dual
UNION ALL SELECT 'DEPRESSION', '당신이 옳다', '정혜신', '해냄출판사', 'https://product.kyobobook.co.kr/detail/S000001026048', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788965746669.jpg', '상대와 나를 이해하는 진정한 공감의 지혜를 전하는 책' FROM dual
UNION ALL SELECT 'ANXIETY', '불안', '알랭 드 보통', '은행나무', 'https://product.kyobobook.co.kr/detail/S000000828225', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788956605593.jpg', '불안의 근원을 찾아 객관적 통찰과 깊은 위안을 주는 책' FROM dual
UNION ALL SELECT 'ANXIETY', '과거가 남긴 우울 미래가 보낸 불안', '김아라', '유노북스', 'https://product.kyobobook.co.kr/detail/S000061451536', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791192300214.jpg', '불안과 우울을 넘어 현재에 집중하도록 돕는 다정한 마음 지침서' FROM dual
UNION ALL SELECT 'ANXIETY', '불안을 알면 흔들리지 않는다', '키렌 슈나크', '오픈도어북스', 'https://product.kyobobook.co.kr/detail/S000218204279', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791173741975.jpg', '불안의 본질을 이해하고 흔들림 속에서도 단단함을 찾는 안내서' FROM dual
UNION ALL SELECT 'ANXIETY', '당신의 불안은 죄가 없다', '웬디 스즈키', '21세기북스', 'https://product.kyobobook.co.kr/detail/S000213834268', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791171176670.jpg', NULL FROM dual
UNION ALL SELECT 'RELATIONSHIP', '나는 왜 네 말이 힘들까', '박재연', '한빛라이프', 'https://product.kyobobook.co.kr/detail/S000001944783', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791190846011.jpg', '관계 속 상처를 보듬고 건강한 대화를 이끄는 통찰의 안내서' FROM dual
UNION ALL SELECT 'RELATIONSHIP', '말센스', '셀레스트 헤들리', '스몰빅라이프', 'https://product.kyobobook.co.kr/detail/S000001898255', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187165460.jpg', '대화의 본질을 깨닫고 관계를 변화시키는 안내서' FROM dual
UNION ALL SELECT 'RELATIONSHIP', '나는 왜 남들보다 쉽게 지칠까', '최재훈', '서스테인', 'https://product.kyobobook.co.kr/detail/S000213675097', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193388075.jpg', '쉽게 지치는 나를 이해하고 보듬어주는 다정한 안내서' FROM dual
UNION ALL SELECT 'RELATIONSHIP', '데일 카네기 인간관계론', '데일 카네기', '현대지성', 'https://product.kyobobook.co.kr/detail/S000001897788', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791187142560.jpg', NULL FROM dual
UNION ALL SELECT 'RELATIONSHIP', '미움받을 용기', '기시미 이치로, 고가 후미타케', '인플루엔셜', 'https://product.kyobobook.co.kr/detail/S000200555616', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791168340770.jpg', '관계 속에서 나를 찾고 행복할 용기를 주는 아들러 심리학 안내서' FROM dual
UNION ALL SELECT 'LETHARGY', '나는 왜 무기력을 되풀이하는가', '에리히 프롬', '나무생각', 'https://product.kyobobook.co.kr/detail/S000001890530', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791186688519.jpg', NULL FROM dual
UNION ALL SELECT 'LETHARGY', '어느 날 갑자기 무기력이 찾아왔다', '클라우스 베른하르트', '동녘라이프', 'https://product.kyobobook.co.kr/detail/S000001449403', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788990514776.jpg', NULL FROM dual
UNION ALL SELECT 'LETHARGY', '무기력이 무기력해지도록', '한창수', '알에이치코리아', 'https://product.kyobobook.co.kr/detail/S000000479280', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925579863.jpg', '무기력의 실체를 이해하고 극복의 길을 제시하는 전문적인 안내서' FROM dual
UNION ALL SELECT 'LETHARGY', '지쳤거나 좋아하는 게 없거나', '글배우', '강한별', 'https://product.kyobobook.co.kr/detail/S000001986809', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791197472558.jpg', '지친 마음을 따뜻하게 위로하고 다시 일어설 용기를 주는 에세이' FROM dual;

COMMIT;

-- =============================================================================
-- [선택] 가벼운 시드 — ISBN이 NULL인 수동 행만 지우고 감정별 5권×4감정(20권) 삽입
--       네이버 캐시(ISBN 있음)는 유지하고 싶을 때: 아래 블록 주석을 해제하고,
--       위 섹션 3 전체(제약 재설정·DELETE·INSERT …)는 실행하지 말 것.
-- =============================================================================
/*
DELETE FROM recommendation_books WHERE isbn IS NULL;

INSERT ALL
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '죽고 싶지만 떡볶이는 먹고 싶어', '백세희', '흔', NULL, NULL, '우울감을 솔직하게 풀어낸 에세이')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '나는 나로 살기로 했다', '김수현', '마음의숲', NULL, NULL, '자기 자신을 사랑하는 법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '감정의 발견', '마크 브래킷', '북라이프', NULL, NULL, '감정을 이해하고 다루는 방법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '우울할 땐 뇌과학', '알렉스 코브', '심심', NULL, NULL, '뇌과학으로 보는 우울증 극복법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('DEPRESSION', '괜찮지 않아도 괜찮아', '최명기', '더퀘스트', NULL, NULL, '있는 그대로의 나를 받아들이는 심리 에세이')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '마음챙김', '마크 윌리엄스', '불광출판사', NULL, NULL, '스트레스 해소를 위한 마음챙김')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '지금 이 순간을 살아라', '에크하르트 톨레', '양문', NULL, NULL, '현재에 집중하는 삶')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '번아웃 사회', '한병철', '문학과지성사', NULL, NULL, '현대 사회의 피로감을 분석')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '쉬어도 피곤한 사람들', '박용철', '21세기북스', NULL, NULL, '번아웃에서 벗어나는 회복 전략')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('STRESS', '번아웃', '에밀리 나고스키', '해나무', NULL, NULL, '완벽주의에서 벗어나 진짜 쉬는 법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '불안', '알랭 드 보통', '은행나무', NULL, NULL, '불안의 본질을 탐구')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '오늘도 불안한 너에게', '박진영', '시공사', NULL, NULL, '불안을 극복하는 실천법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '명상록', '마르쿠스 아우렐리우스', '현대지성', NULL, NULL, '내면의 평화를 위한 철학적 성찰')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '걱정 끄기 연습', '쑤언 수치', '유노북스', NULL, NULL, '걱정을 줄이는 심리 기법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('ANXIETY', '불안해도 괜찮아', '클라우스 베른하르트', '갈매나무', NULL, NULL, '불안 장애를 스스로 극복하는 인지 훈련법')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '아주 작은 습관의 힘', '제임스 클리어', '비즈니스북스', NULL, NULL, '작은 습관으로 큰 변화를')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '미라클 모닝', '할 엘로드', '한빛비즈', NULL, NULL, '아침을 바꾸면 인생이 바뀐다')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '그릿', '앤절라 더크워스', '비즈니스북스', NULL, NULL, '끝까지 해내는 힘의 비밀')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '내가 확실히 알고 있는 것들', '오프라 윈프리', '북하우스', NULL, NULL, '삶을 다시 시작하게 해주는 이야기')
    INTO recommendation_books (emotion, title, author, publisher, link, image, description)
        VALUES ('LETHARGY', '게으름에 대한 찬양', '버트런드 러셀', '사회평론', NULL, NULL, '진정한 휴식과 활력을 되찾는 철학적 에세이')
SELECT 1 FROM DUAL;

COMMIT;
*/
